// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/features/ai/domain/usecases/send_message_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aipet_frontend/features/ai/domain/entities/entities.dart'
    as _i2;
import 'package:aipet_frontend/features/ai/domain/repositories/ai_repository.dart'
    as _i3;
import 'package:aipet_frontend/shared/domain/entities/entities.dart' as _i7;
import 'package:aipet_frontend/shared/foundation/result/app_result.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAiChatSessionEntity_0 extends _i1.SmartFake
    implements _i2.AiChatSessionEntity {
  _FakeAiChatSessionEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiFavoriteEntity_1 extends _i1.SmartFake
    implements _i2.AiFavoriteEntity {
  _FakeAiFavoriteEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSummaryEntity_2 extends _i1.SmartFake
    implements _i2.AiChatSummaryEntity {
  _FakeAiChatSummaryEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSummary_3 extends _i1.SmartFake implements _i2.AiChatSummary {
  _FakeAiChatSummary_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiRepository extends _i1.Mock implements _i3.AiRepository {
  MockAiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.AiMessageEntity>> getChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistory, []),
            returnValue: _i4.Future<List<_i2.AiMessageEntity>>.value(
              <_i2.AiMessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.AiMessageEntity>>);

  @override
  _i4.Future<_i5.Result<_i2.AiMessageEntity>> sendMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i4.Future<_i5.Result<_i2.AiMessageEntity>>.value(
              _i6.dummyValue<_i5.Result<_i2.AiMessageEntity>>(
                this,
                Invocation.method(#sendMessage, [message]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i2.AiMessageEntity>>);

  @override
  _i4.Future<_i5.Result<_i2.AiMessageEntity>> sendMessageWithPetContext(
    String? message, {
    _i7.PetProfileEntity? petContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessageWithPetContext,
              [message],
              {#petContext: petContext},
            ),
            returnValue: _i4.Future<_i5.Result<_i2.AiMessageEntity>>.value(
              _i6.dummyValue<_i5.Result<_i2.AiMessageEntity>>(
                this,
                Invocation.method(
                  #sendMessageWithPetContext,
                  [message],
                  {#petContext: petContext},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i2.AiMessageEntity>>);

  @override
  _i4.Future<void> clearChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearChatHistory, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.AiChatSessionEntity>> getChatSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getChatSessions, []),
            returnValue: _i4.Future<List<_i2.AiChatSessionEntity>>.value(
              <_i2.AiChatSessionEntity>[],
            ),
          )
          as _i4.Future<List<_i2.AiChatSessionEntity>>);

  @override
  _i4.Future<_i2.AiChatSessionEntity> createChatSession(
    String? title, {
    String? petId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChatSession, [title], {#petId: petId}),
            returnValue: _i4.Future<_i2.AiChatSessionEntity>.value(
              _FakeAiChatSessionEntity_0(
                this,
                Invocation.method(#createChatSession, [title], {#petId: petId}),
              ),
            ),
          )
          as _i4.Future<_i2.AiChatSessionEntity>);

  @override
  _i4.Future<void> deleteChatSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatSession, [sessionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.AiSuggestedQuestionEntity>> getSuggestedQuestions() =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedQuestions, []),
            returnValue: _i4.Future<List<_i2.AiSuggestedQuestionEntity>>.value(
              <_i2.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i4.Future<List<_i2.AiSuggestedQuestionEntity>>);

  @override
  _i4.Future<List<_i2.AiSuggestedQuestionEntity>>
  getPersonalizedSuggestedQuestions({
    String? category,
    _i7.PetProfileEntity? pet,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonalizedSuggestedQuestions, [], {
              #category: category,
              #pet: pet,
            }),
            returnValue: _i4.Future<List<_i2.AiSuggestedQuestionEntity>>.value(
              <_i2.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i4.Future<List<_i2.AiSuggestedQuestionEntity>>);

  @override
  _i4.Future<_i2.AiFavoriteEntity> addFavoriteMessage(
    _i2.AiMessageEntity? message,
    String? category, {
    String? petId,
    String? petName,
    String? userNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addFavoriteMessage,
              [message, category],
              {#petId: petId, #petName: petName, #userNote: userNote},
            ),
            returnValue: _i4.Future<_i2.AiFavoriteEntity>.value(
              _FakeAiFavoriteEntity_1(
                this,
                Invocation.method(
                  #addFavoriteMessage,
                  [message, category],
                  {#petId: petId, #petName: petName, #userNote: userNote},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.AiFavoriteEntity>);

  @override
  _i4.Future<void> removeFavoriteMessage(String? favoriteId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavoriteMessage, [favoriteId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.AiFavoriteEntity>> getFavoriteMessages({
    String? petId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteMessages, [], {
              #petId: petId,
              #category: category,
            }),
            returnValue: _i4.Future<List<_i2.AiFavoriteEntity>>.value(
              <_i2.AiFavoriteEntity>[],
            ),
          )
          as _i4.Future<List<_i2.AiFavoriteEntity>>);

  @override
  List<_i2.AiFavoriteQaEntity> getFavoriteQAs() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteQAs, []),
            returnValue: <_i2.AiFavoriteQaEntity>[],
          )
          as List<_i2.AiFavoriteQaEntity>);

  @override
  _i4.Future<_i2.AiChatSummaryEntity> createChatSummary(
    List<_i2.AiMessageEntity>? messages,
    String? category, {
    String? petId,
    String? petName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createChatSummary,
              [messages, category],
              {#petId: petId, #petName: petName},
            ),
            returnValue: _i4.Future<_i2.AiChatSummaryEntity>.value(
              _FakeAiChatSummaryEntity_2(
                this,
                Invocation.method(
                  #createChatSummary,
                  [messages, category],
                  {#petId: petId, #petName: petName},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.AiChatSummaryEntity>);

  @override
  _i4.Future<List<_i2.AiChatSummaryEntity>> getChatSummaries({
    String? petId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatSummaries, [], {
              #petId: petId,
              #category: category,
            }),
            returnValue: _i4.Future<List<_i2.AiChatSummaryEntity>>.value(
              <_i2.AiChatSummaryEntity>[],
            ),
          )
          as _i4.Future<List<_i2.AiChatSummaryEntity>>);

  @override
  _i4.Future<void> deleteChatSummary(String? summaryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatSummary, [summaryId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveChatHistory(_i2.AiChatHistoryEntity? chatHistory) =>
      (super.noSuchMethod(
            Invocation.method(#saveChatHistory, [chatHistory]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AiChatSummary> generateChatSummary({
    required List<String>? userMessages,
    required String? petName,
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateChatSummary, [], {
              #userMessages: userMessages,
              #petName: petName,
              #category: category,
            }),
            returnValue: _i4.Future<_i2.AiChatSummary>.value(
              _FakeAiChatSummary_3(
                this,
                Invocation.method(#generateChatSummary, [], {
                  #userMessages: userMessages,
                  #petName: petName,
                  #category: category,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AiChatSummary>);

  @override
  _i4.Future<List<_i2.AiChatHistoryEntity>> getChatHistories({
    int? limit = 30,
    bool? onlyManualSaved = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistories, [], {
              #limit: limit,
              #onlyManualSaved: onlyManualSaved,
            }),
            returnValue: _i4.Future<List<_i2.AiChatHistoryEntity>>.value(
              <_i2.AiChatHistoryEntity>[],
            ),
          )
          as _i4.Future<List<_i2.AiChatHistoryEntity>>);

  @override
  _i4.Future<void> deleteChatHistory(String? historyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatHistory, [historyId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.Result<List<_i2.AiMessageEntity>>> loadChatHistory({
    required String? userId,
    String? petId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadChatHistory, [], {
              #userId: userId,
              #petId: petId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i4.Future<_i5.Result<List<_i2.AiMessageEntity>>>.value(
                  _i6.dummyValue<_i5.Result<List<_i2.AiMessageEntity>>>(
                    this,
                    Invocation.method(#loadChatHistory, [], {
                      #userId: userId,
                      #petId: petId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i2.AiMessageEntity>>>);

  @override
  _i4.Future<_i5.Result<_i2.AiAnalysisEntity>> analyzeMessage({
    required String? message,
    String? petId,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeMessage, [], {
              #message: message,
              #petId: petId,
              #context: context,
            }),
            returnValue: _i4.Future<_i5.Result<_i2.AiAnalysisEntity>>.value(
              _i6.dummyValue<_i5.Result<_i2.AiAnalysisEntity>>(
                this,
                Invocation.method(#analyzeMessage, [], {
                  #message: message,
                  #petId: petId,
                  #context: context,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i2.AiAnalysisEntity>>);

  @override
  _i4.Future<_i5.Result<_i2.AiMessageEntity>> sendMessageWithParams({
    required String? message,
    required String? petId,
    String? categoryId,
    List<String>? attachedImages,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessageWithParams, [], {
              #message: message,
              #petId: petId,
              #categoryId: categoryId,
              #attachedImages: attachedImages,
            }),
            returnValue: _i4.Future<_i5.Result<_i2.AiMessageEntity>>.value(
              _i6.dummyValue<_i5.Result<_i2.AiMessageEntity>>(
                this,
                Invocation.method(#sendMessageWithParams, [], {
                  #message: message,
                  #petId: petId,
                  #categoryId: categoryId,
                  #attachedImages: attachedImages,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i2.AiMessageEntity>>);

  @override
  _i4.Future<_i5.Result<bool>> toggleFavoriteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavoriteMessage, [messageId]),
            returnValue: _i4.Future<_i5.Result<bool>>.value(
              _i6.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#toggleFavoriteMessage, [messageId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool>>);

  @override
  _i4.Future<_i5.Result<List<_i2.AiSuggestedQuestionEntity>>>
  getSuggestedQuestionsWithParams({String? petId, String? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedQuestionsWithParams, [], {
              #petId: petId,
              #categoryId: categoryId,
            }),
            returnValue:
                _i4.Future<
                  _i5.Result<List<_i2.AiSuggestedQuestionEntity>>
                >.value(
                  _i6.dummyValue<
                    _i5.Result<List<_i2.AiSuggestedQuestionEntity>>
                  >(
                    this,
                    Invocation.method(#getSuggestedQuestionsWithParams, [], {
                      #petId: petId,
                      #categoryId: categoryId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i2.AiSuggestedQuestionEntity>>>);
}
