// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/lib_mockito_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aipet_frontend/features/ai/data/services/openai_service.dart'
    as _i10;
import 'package:aipet_frontend/features/ai/domain/entities/entities.dart'
    as _i2;
import 'package:aipet_frontend/features/ai/domain/repositories/ai_repository.dart'
    as _i6;
import 'package:aipet_frontend/features/auth/domain/repositories/auth_repository.dart'
    as _i11;
import 'package:aipet_frontend/features/home/domain/entities/entities.dart'
    as _i4;
import 'package:aipet_frontend/features/home/domain/repositories/home_repository.dart'
    as _i12;
import 'package:aipet_frontend/features/pet_registor/domain/entities/pet_profile_entity.dart'
    as _i9;
import 'package:aipet_frontend/features/pet_registor/domain/repositories/pet_repository.dart'
    as _i13;
import 'package:aipet_frontend/features/walk/domain/entities/walk_record_entity.dart'
    as _i5;
import 'package:aipet_frontend/features/walk/domain/repositories/walk_repository.dart'
    as _i14;
import 'package:aipet_frontend/features/walk/domain/services/walk_route_service.dart'
    as _i15;
import 'package:aipet_frontend/shared/foundation/result/app_result.dart' as _i7;
import 'package:aipet_frontend/shared/shared.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAiChatSessionEntity_0 extends _i1.SmartFake
    implements _i2.AiChatSessionEntity {
  _FakeAiChatSessionEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiFavoriteEntity_1 extends _i1.SmartFake
    implements _i2.AiFavoriteEntity {
  _FakeAiFavoriteEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSummaryEntity_2 extends _i1.SmartFake
    implements _i2.AiChatSummaryEntity {
  _FakeAiChatSummaryEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSummary_3 extends _i1.SmartFake implements _i2.AiChatSummary {
  _FakeAiChatSummary_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_4<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeDashboardEntity_5 extends _i1.SmartFake
    implements _i4.HomeDashboardEntity {
  _FakeHomeDashboardEntity_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalkSummary_6 extends _i1.SmartFake implements _i4.WalkSummary {
  _FakeWalkSummary_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthSummary_7 extends _i1.SmartFake implements _i4.HealthSummary {
  _FakeHealthSummary_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalkRecordEntity_8 extends _i1.SmartFake
    implements _i5.WalkRecordEntity {
  _FakeWalkRecordEntity_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_9 extends _i1.SmartFake implements Duration {
  _FakeDuration_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiRepository extends _i1.Mock implements _i6.AiRepository {
  MockAiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.AiMessageEntity>> getChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistory, []),
            returnValue: _i3.Future<List<_i2.AiMessageEntity>>.value(
              <_i2.AiMessageEntity>[],
            ),
          )
          as _i3.Future<List<_i2.AiMessageEntity>>);

  @override
  _i3.Future<_i7.Result<_i2.AiMessageEntity>> sendMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i3.Future<_i7.Result<_i2.AiMessageEntity>>.value(
              _i8.dummyValue<_i7.Result<_i2.AiMessageEntity>>(
                this,
                Invocation.method(#sendMessage, [message]),
              ),
            ),
          )
          as _i3.Future<_i7.Result<_i2.AiMessageEntity>>);

  @override
  _i3.Future<_i7.Result<_i2.AiMessageEntity>> sendMessageWithPetContext(
    String? message, {
    _i9.PetProfileEntity? petContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessageWithPetContext,
              [message],
              {#petContext: petContext},
            ),
            returnValue: _i3.Future<_i7.Result<_i2.AiMessageEntity>>.value(
              _i8.dummyValue<_i7.Result<_i2.AiMessageEntity>>(
                this,
                Invocation.method(
                  #sendMessageWithPetContext,
                  [message],
                  {#petContext: petContext},
                ),
              ),
            ),
          )
          as _i3.Future<_i7.Result<_i2.AiMessageEntity>>);

  @override
  _i3.Future<void> clearChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearChatHistory, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.AiChatSessionEntity>> getChatSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getChatSessions, []),
            returnValue: _i3.Future<List<_i2.AiChatSessionEntity>>.value(
              <_i2.AiChatSessionEntity>[],
            ),
          )
          as _i3.Future<List<_i2.AiChatSessionEntity>>);

  @override
  _i3.Future<_i2.AiChatSessionEntity> createChatSession(
    String? title, {
    String? petId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChatSession, [title], {#petId: petId}),
            returnValue: _i3.Future<_i2.AiChatSessionEntity>.value(
              _FakeAiChatSessionEntity_0(
                this,
                Invocation.method(#createChatSession, [title], {#petId: petId}),
              ),
            ),
          )
          as _i3.Future<_i2.AiChatSessionEntity>);

  @override
  _i3.Future<void> deleteChatSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatSession, [sessionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.AiSuggestedQuestionEntity>> getSuggestedQuestions() =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedQuestions, []),
            returnValue: _i3.Future<List<_i2.AiSuggestedQuestionEntity>>.value(
              <_i2.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i3.Future<List<_i2.AiSuggestedQuestionEntity>>);

  @override
  _i3.Future<List<_i2.AiSuggestedQuestionEntity>>
  getPersonalizedSuggestedQuestions({
    String? category,
    _i9.PetProfileEntity? pet,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonalizedSuggestedQuestions, [], {
              #category: category,
              #pet: pet,
            }),
            returnValue: _i3.Future<List<_i2.AiSuggestedQuestionEntity>>.value(
              <_i2.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i3.Future<List<_i2.AiSuggestedQuestionEntity>>);

  @override
  _i3.Future<_i2.AiFavoriteEntity> addFavoriteMessage(
    _i2.AiMessageEntity? message,
    String? category, {
    String? petId,
    String? petName,
    String? userNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addFavoriteMessage,
              [message, category],
              {#petId: petId, #petName: petName, #userNote: userNote},
            ),
            returnValue: _i3.Future<_i2.AiFavoriteEntity>.value(
              _FakeAiFavoriteEntity_1(
                this,
                Invocation.method(
                  #addFavoriteMessage,
                  [message, category],
                  {#petId: petId, #petName: petName, #userNote: userNote},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.AiFavoriteEntity>);

  @override
  _i3.Future<void> removeFavoriteMessage(String? favoriteId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavoriteMessage, [favoriteId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.AiFavoriteEntity>> getFavoriteMessages({
    String? petId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteMessages, [], {
              #petId: petId,
              #category: category,
            }),
            returnValue: _i3.Future<List<_i2.AiFavoriteEntity>>.value(
              <_i2.AiFavoriteEntity>[],
            ),
          )
          as _i3.Future<List<_i2.AiFavoriteEntity>>);

  @override
  List<_i2.AiFavoriteQaEntity> getFavoriteQAs() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteQAs, []),
            returnValue: <_i2.AiFavoriteQaEntity>[],
          )
          as List<_i2.AiFavoriteQaEntity>);

  @override
  _i3.Future<_i2.AiChatSummaryEntity> createChatSummary(
    List<_i2.AiMessageEntity>? messages,
    String? category, {
    String? petId,
    String? petName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createChatSummary,
              [messages, category],
              {#petId: petId, #petName: petName},
            ),
            returnValue: _i3.Future<_i2.AiChatSummaryEntity>.value(
              _FakeAiChatSummaryEntity_2(
                this,
                Invocation.method(
                  #createChatSummary,
                  [messages, category],
                  {#petId: petId, #petName: petName},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.AiChatSummaryEntity>);

  @override
  _i3.Future<List<_i2.AiChatSummaryEntity>> getChatSummaries({
    String? petId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatSummaries, [], {
              #petId: petId,
              #category: category,
            }),
            returnValue: _i3.Future<List<_i2.AiChatSummaryEntity>>.value(
              <_i2.AiChatSummaryEntity>[],
            ),
          )
          as _i3.Future<List<_i2.AiChatSummaryEntity>>);

  @override
  _i3.Future<void> deleteChatSummary(String? summaryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatSummary, [summaryId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveChatHistory(_i2.AiChatHistoryEntity? chatHistory) =>
      (super.noSuchMethod(
            Invocation.method(#saveChatHistory, [chatHistory]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.AiChatSummary> generateChatSummary({
    required List<String>? userMessages,
    required String? petName,
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateChatSummary, [], {
              #userMessages: userMessages,
              #petName: petName,
              #category: category,
            }),
            returnValue: _i3.Future<_i2.AiChatSummary>.value(
              _FakeAiChatSummary_3(
                this,
                Invocation.method(#generateChatSummary, [], {
                  #userMessages: userMessages,
                  #petName: petName,
                  #category: category,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.AiChatSummary>);

  @override
  _i3.Future<List<_i2.AiChatHistoryEntity>> getChatHistories({
    int? limit = 30,
    bool? onlyManualSaved = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistories, [], {
              #limit: limit,
              #onlyManualSaved: onlyManualSaved,
            }),
            returnValue: _i3.Future<List<_i2.AiChatHistoryEntity>>.value(
              <_i2.AiChatHistoryEntity>[],
            ),
          )
          as _i3.Future<List<_i2.AiChatHistoryEntity>>);

  @override
  _i3.Future<void> deleteChatHistory(String? historyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatHistory, [historyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [OpenAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAIService extends _i1.Mock implements _i10.OpenAIService {
  MockOpenAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> generateResponse(
    String? message, {
    _i9.PetProfileEntity? petContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateResponse,
              [message],
              {#petContext: petContext},
            ),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #generateResponse,
                  [message],
                  {#petContext: petContext},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  void logError(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#logError, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void logInfo(String? message) => super.noSuchMethod(
    Invocation.method(#logInfo, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logWarning(String? message) => super.noSuchMethod(
    Invocation.method(#logWarning, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logDebug(String? message) => super.noSuchMethod(
    Invocation.method(#logDebug, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void recordPerformanceMetric(String? operation, Duration? duration) =>
      super.noSuchMethod(
        Invocation.method(#recordPerformanceMetric, [operation, duration]),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<T> trackApiPerformance<T>(
    String? operation,
    _i3.Future<T> Function()? apiCall,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#trackApiPerformance, [operation, apiCall]),
            returnValue:
                _i8.ifNotNull(
                  _i8.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#trackApiPerformance, [
                      operation,
                      apiCall,
                    ]),
                  ),
                  (T v) => _i3.Future<T>.value(v),
                ) ??
                _FakeFuture_4<T>(
                  this,
                  Invocation.method(#trackApiPerformance, [operation, apiCall]),
                ),
          )
          as _i3.Future<T>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i11.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i7.Result<_i11.AuthUser>> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i3.Future<_i7.Result<_i11.AuthUser>>.value(
              _i8.dummyValue<_i7.Result<_i11.AuthUser>>(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i3.Future<_i7.Result<_i11.AuthUser>>);

  @override
  _i3.Future<_i7.Result<_i11.AuthUser>> createUserWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i3.Future<_i7.Result<_i11.AuthUser>>.value(
              _i8.dummyValue<_i7.Result<_i11.AuthUser>>(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i3.Future<_i7.Result<_i11.AuthUser>>);

  @override
  _i3.Future<_i7.Result<_i11.AuthUser>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i7.Result<_i11.AuthUser>>.value(
              _i8.dummyValue<_i7.Result<_i11.AuthUser>>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i3.Future<_i7.Result<_i11.AuthUser>>);

  @override
  _i3.Future<_i7.Result<_i11.AuthUser>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i3.Future<_i7.Result<_i11.AuthUser>>.value(
              _i8.dummyValue<_i7.Result<_i11.AuthUser>>(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
          )
          as _i3.Future<_i7.Result<_i11.AuthUser>>);

  @override
  _i3.Future<_i7.Result<_i11.AuthUser>> signInWithLine() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithLine, []),
            returnValue: _i3.Future<_i7.Result<_i11.AuthUser>>.value(
              _i8.dummyValue<_i7.Result<_i11.AuthUser>>(
                this,
                Invocation.method(#signInWithLine, []),
              ),
            ),
          )
          as _i3.Future<_i7.Result<_i11.AuthUser>>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i11.AuthUser?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i3.Future<_i11.AuthUser?>.value(),
          )
          as _i3.Future<_i11.AuthUser?>);

  @override
  _i3.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> exchangeServerToken(String? idToken) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeServerToken, [idToken]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#exchangeServerToken, [idToken]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String?> getCurrentUserIdToken() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserIdToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> getStoredServerToken() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredServerToken, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> saveServerToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveServerToken, [token]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearServerToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearServerToken, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i12.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.HomeDashboardEntity> getDashboardData() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardData, []),
            returnValue: _i3.Future<_i4.HomeDashboardEntity>.value(
              _FakeHomeDashboardEntity_5(
                this,
                Invocation.method(#getDashboardData, []),
              ),
            ),
          )
          as _i3.Future<_i4.HomeDashboardEntity>);

  @override
  _i3.Future<_i4.WeatherEntity?> getCurrentWeather({
    _i4.WeatherLocationEntity? location,
    bool? userTriggered = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWeather, [], {
              #location: location,
              #userTriggered: userTriggered,
            }),
            returnValue: _i3.Future<_i4.WeatherEntity?>.value(),
          )
          as _i3.Future<_i4.WeatherEntity?>);

  @override
  _i3.Future<List<_i4.PetSummaryEntity>> getPetSummaries() =>
      (super.noSuchMethod(
            Invocation.method(#getPetSummaries, []),
            returnValue: _i3.Future<List<_i4.PetSummaryEntity>>.value(
              <_i4.PetSummaryEntity>[],
            ),
          )
          as _i3.Future<List<_i4.PetSummaryEntity>>);

  @override
  _i3.Future<_i4.WalkSummary> getWalkSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getWalkSummary, []),
            returnValue: _i3.Future<_i4.WalkSummary>.value(
              _FakeWalkSummary_6(this, Invocation.method(#getWalkSummary, [])),
            ),
          )
          as _i3.Future<_i4.WalkSummary>);

  @override
  _i3.Future<_i4.HealthSummary> getPetHealthSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getPetHealthSummary, []),
            returnValue: _i3.Future<_i4.HealthSummary>.value(
              _FakeHealthSummary_7(
                this,
                Invocation.method(#getPetHealthSummary, []),
              ),
            ),
          )
          as _i3.Future<_i4.HealthSummary>);

  @override
  _i3.Future<List<_i4.AppointmentSummary>> getUpcomingAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingAppointments, []),
            returnValue: _i3.Future<List<_i4.AppointmentSummary>>.value(
              <_i4.AppointmentSummary>[],
            ),
          )
          as _i3.Future<List<_i4.AppointmentSummary>>);
}

/// A class which mocks [PetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetRepository extends _i1.Mock implements _i13.PetRepository {
  MockPetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i7.Result<List<_i9.PetProfileEntity>>> getAllPets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPets, []),
            returnValue:
                _i3.Future<_i7.Result<List<_i9.PetProfileEntity>>>.value(
                  _i8.dummyValue<_i7.Result<List<_i9.PetProfileEntity>>>(
                    this,
                    Invocation.method(#getAllPets, []),
                  ),
                ),
          )
          as _i3.Future<_i7.Result<List<_i9.PetProfileEntity>>>);

  @override
  _i3.Future<_i7.Result<_i9.PetProfileEntity?>> getPetById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPetById, [id]),
            returnValue: _i3.Future<_i7.Result<_i9.PetProfileEntity?>>.value(
              _i8.dummyValue<_i7.Result<_i9.PetProfileEntity?>>(
                this,
                Invocation.method(#getPetById, [id]),
              ),
            ),
          )
          as _i3.Future<_i7.Result<_i9.PetProfileEntity?>>);

  @override
  _i3.Future<_i7.Result<_i9.PetProfileEntity>> createPet(
    _i9.PetProfileEntity? pet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPet, [pet]),
            returnValue: _i3.Future<_i7.Result<_i9.PetProfileEntity>>.value(
              _i8.dummyValue<_i7.Result<_i9.PetProfileEntity>>(
                this,
                Invocation.method(#createPet, [pet]),
              ),
            ),
          )
          as _i3.Future<_i7.Result<_i9.PetProfileEntity>>);

  @override
  _i3.Future<_i7.Result<_i9.PetProfileEntity>> updatePet(
    _i9.PetProfileEntity? pet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePet, [pet]),
            returnValue: _i3.Future<_i7.Result<_i9.PetProfileEntity>>.value(
              _i8.dummyValue<_i7.Result<_i9.PetProfileEntity>>(
                this,
                Invocation.method(#updatePet, [pet]),
              ),
            ),
          )
          as _i3.Future<_i7.Result<_i9.PetProfileEntity>>);

  @override
  _i3.Future<_i7.Result<void>> deletePet(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePet, [id]),
            returnValue: _i3.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#deletePet, [id]),
              ),
            ),
          )
          as _i3.Future<_i7.Result<void>>);

  @override
  _i3.Future<void> saveTemporaryPetData(dynamic data) =>
      (super.noSuchMethod(
            Invocation.method(#saveTemporaryPetData, [data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<dynamic> getTemporaryPetData() =>
      (super.noSuchMethod(
            Invocation.method(#getTemporaryPetData, []),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<void> clearTemporaryPetData() =>
      (super.noSuchMethod(
            Invocation.method(#clearTemporaryPetData, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [WalkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalkRepository extends _i1.Mock implements _i14.WalkRepository {
  MockWalkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.WalkRecordEntity>> getAllWalkRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWalkRecords, []),
            returnValue: _i3.Future<List<_i5.WalkRecordEntity>>.value(
              <_i5.WalkRecordEntity>[],
            ),
          )
          as _i3.Future<List<_i5.WalkRecordEntity>>);

  @override
  _i3.Future<List<_i5.WalkRecordEntity>> getWalkRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getWalkRecords, []),
            returnValue: _i3.Future<List<_i5.WalkRecordEntity>>.value(
              <_i5.WalkRecordEntity>[],
            ),
          )
          as _i3.Future<List<_i5.WalkRecordEntity>>);

  @override
  _i3.Future<_i5.WalkRecordEntity?> getWalkRecordById(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#getWalkRecordById, [recordId]),
            returnValue: _i3.Future<_i5.WalkRecordEntity?>.value(),
          )
          as _i3.Future<_i5.WalkRecordEntity?>);

  @override
  _i3.Future<List<_i5.WalkRecordEntity>> getWalkRecordsByPetId(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#getWalkRecordsByPetId, [petId]),
            returnValue: _i3.Future<List<_i5.WalkRecordEntity>>.value(
              <_i5.WalkRecordEntity>[],
            ),
          )
          as _i3.Future<List<_i5.WalkRecordEntity>>);

  @override
  _i3.Future<_i5.WalkRecordEntity?> getCurrentWalk() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWalk, []),
            returnValue: _i3.Future<_i5.WalkRecordEntity?>.value(),
          )
          as _i3.Future<_i5.WalkRecordEntity?>);

  @override
  _i3.Future<_i5.WalkRecordEntity> startWalk(
    _i5.WalkRecordEntity? walkRecord,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startWalk, [walkRecord]),
            returnValue: _i3.Future<_i5.WalkRecordEntity>.value(
              _FakeWalkRecordEntity_8(
                this,
                Invocation.method(#startWalk, [walkRecord]),
              ),
            ),
          )
          as _i3.Future<_i5.WalkRecordEntity>);

  @override
  _i3.Future<void> saveWalkRecord(_i5.WalkRecordEntity? walkRecord) =>
      (super.noSuchMethod(
            Invocation.method(#saveWalkRecord, [walkRecord]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateWalkRecord(_i5.WalkRecordEntity? walkRecord) =>
      (super.noSuchMethod(
            Invocation.method(#updateWalkRecord, [walkRecord]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteWalkRecord(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWalkRecord, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.WalkRecordEntity> endWalk(
    String? recordId, {
    double? distance,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #endWalk,
              [recordId],
              {#distance: distance, #notes: notes},
            ),
            returnValue: _i3.Future<_i5.WalkRecordEntity>.value(
              _FakeWalkRecordEntity_8(
                this,
                Invocation.method(
                  #endWalk,
                  [recordId],
                  {#distance: distance, #notes: notes},
                ),
              ),
            ),
          )
          as _i3.Future<_i5.WalkRecordEntity>);

  @override
  _i3.Future<dynamic> getWalkStatistics({
    String? petId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWalkStatistics, [], {
              #petId: petId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);
}

/// A class which mocks [WalkRouteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalkRouteService extends _i1.Mock implements _i15.WalkRouteService {
  MockWalkRouteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double calculateTotalDistance(List<dynamic>? route) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTotalDistance, [route]),
            returnValue: 0.0,
          )
          as double);

  @override
  Duration calculateTotalDuration(List<dynamic>? route) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTotalDuration, [route]),
            returnValue: _FakeDuration_9(
              this,
              Invocation.method(#calculateTotalDuration, [route]),
            ),
          )
          as Duration);

  @override
  double calculateAverageSpeed(List<dynamic>? route) =>
      (super.noSuchMethod(
            Invocation.method(#calculateAverageSpeed, [route]),
            returnValue: 0.0,
          )
          as double);

  @override
  String encodePolyline(List<dynamic>? route) =>
      (super.noSuchMethod(
            Invocation.method(#encodePolyline, [route]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#encodePolyline, [route]),
            ),
          )
          as String);

  @override
  List<dynamic> decodePolyline(String? encodedPolyline) =>
      (super.noSuchMethod(
            Invocation.method(#decodePolyline, [encodedPolyline]),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<dynamic> optimizeRoute(List<dynamic>? route) =>
      (super.noSuchMethod(
            Invocation.method(#optimizeRoute, [route]),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<dynamic> smoothRoute(List<dynamic>? route) =>
      (super.noSuchMethod(
            Invocation.method(#smoothRoute, [route]),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);
}

/// A class which mocks [ValidationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidationService extends _i1.Mock implements _i16.ValidationService {
  MockValidationService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [CommonErrorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommonErrorService extends _i1.Mock
    implements _i16.CommonErrorService {
  MockCommonErrorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i16.ErrorInfo> get errorStream =>
      (super.noSuchMethod(
            Invocation.getter(#errorStream),
            returnValue: _i3.Stream<_i16.ErrorInfo>.empty(),
          )
          as _i3.Stream<_i16.ErrorInfo>);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> handleErrorInstance(
    dynamic error, {
    String? message,
    _i16.ErrorSeverity? severity = _i16.ErrorSeverity.medium,
    _i16.ErrorType? type = _i16.ErrorType.unknown,
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #handleErrorInstance,
              [error],
              {
                #message: message,
                #severity: severity,
                #type: type,
                #context: context,
                #stackTrace: stackTrace,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  Map<String, dynamic> getErrorStats() =>
      (super.noSuchMethod(
            Invocation.method(#getErrorStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<_i16.ErrorInfo> getErrorHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getErrorHistory, []),
            returnValue: <_i16.ErrorInfo>[],
          )
          as List<_i16.ErrorInfo>);

  @override
  int getErrorCountByType(_i16.ErrorType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getErrorCountByType, [type]),
            returnValue: 0,
          )
          as int);

  @override
  int getErrorCountBySeverity(_i16.ErrorSeverity? severity) =>
      (super.noSuchMethod(
            Invocation.method(#getErrorCountBySeverity, [severity]),
            returnValue: 0,
          )
          as int);

  @override
  void setEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void clearErrorHistory() => super.noSuchMethod(
    Invocation.method(#clearErrorHistory, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUiService extends _i1.Mock implements _i16.UiService {
  MockUiService() {
    _i1.throwOnMissingStub(this);
  }
}
