// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/lib_mockito_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:aipet_frontend/features/ai/data/services/openai_service.dart'
    as _i11;
import 'package:aipet_frontend/features/ai/domain/entities/entities.dart'
    as _i3;
import 'package:aipet_frontend/features/ai/domain/repositories/ai_repository.dart'
    as _i8;
import 'package:aipet_frontend/features/auth/domain/repositories/auth_repository.dart'
    as _i4;
import 'package:aipet_frontend/features/home/domain/entities/entities.dart'
    as _i5;
import 'package:aipet_frontend/features/home/domain/repositories/home_repository.dart'
    as _i13;
import 'package:aipet_frontend/features/pet_registor/pet_registor.dart' as _i10;
import 'package:aipet_frontend/features/walk/domain/entities/walk_location_entity.dart'
    as _i16;
import 'package:aipet_frontend/features/walk/domain/entities/walk_record_entity.dart'
    as _i6;
import 'package:aipet_frontend/features/walk/domain/entities/walk_statistics_entity.dart'
    as _i7;
import 'package:aipet_frontend/features/walk/domain/repositories/walk_repository.dart'
    as _i14;
import 'package:aipet_frontend/features/walk/domain/services/walk_route_service.dart'
    as _i15;
import 'package:aipet_frontend/shared/shared.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSessionEntity_1 extends _i1.SmartFake
    implements _i3.AiChatSessionEntity {
  _FakeAiChatSessionEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiFavoriteEntity_2 extends _i1.SmartFake
    implements _i3.AiFavoriteEntity {
  _FakeAiFavoriteEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSummaryEntity_3 extends _i1.SmartFake
    implements _i3.AiChatSummaryEntity {
  _FakeAiChatSummaryEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSummary_4 extends _i1.SmartFake implements _i3.AiChatSummary {
  _FakeAiChatSummary_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_5 extends _i1.SmartFake implements _i4.AuthResult {
  _FakeAuthResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeDashboardEntity_6 extends _i1.SmartFake
    implements _i5.HomeDashboardEntity {
  _FakeHomeDashboardEntity_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalkSummary_7 extends _i1.SmartFake implements _i5.WalkSummary {
  _FakeWalkSummary_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthSummary_8 extends _i1.SmartFake implements _i5.HealthSummary {
  _FakeHealthSummary_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalkRecordEntity_9 extends _i1.SmartFake
    implements _i6.WalkRecordEntity {
  _FakeWalkRecordEntity_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalkStatistics_10 extends _i1.SmartFake
    implements _i7.WalkStatistics {
  _FakeWalkStatistics_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_11 extends _i1.SmartFake implements Duration {
  _FakeDuration_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiRepository extends _i1.Mock implements _i8.AiRepository {
  MockAiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i3.AiMessageEntity>> getChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistory, []),
            returnValue: _i9.Future<List<_i3.AiMessageEntity>>.value(
              <_i3.AiMessageEntity>[],
            ),
          )
          as _i9.Future<List<_i3.AiMessageEntity>>);

  @override
  _i9.Future<_i2.Result<_i3.AiMessageEntity>> sendMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i9.Future<_i2.Result<_i3.AiMessageEntity>>.value(
              _FakeResult_0<_i3.AiMessageEntity>(
                this,
                Invocation.method(#sendMessage, [message]),
              ),
            ),
          )
          as _i9.Future<_i2.Result<_i3.AiMessageEntity>>);

  @override
  _i9.Future<_i2.Result<_i3.AiMessageEntity>> sendMessageWithPetContext(
    String? message, {
    _i10.PetProfileEntity? petContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessageWithPetContext,
              [message],
              {#petContext: petContext},
            ),
            returnValue: _i9.Future<_i2.Result<_i3.AiMessageEntity>>.value(
              _FakeResult_0<_i3.AiMessageEntity>(
                this,
                Invocation.method(
                  #sendMessageWithPetContext,
                  [message],
                  {#petContext: petContext},
                ),
              ),
            ),
          )
          as _i9.Future<_i2.Result<_i3.AiMessageEntity>>);

  @override
  _i9.Future<void> clearChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearChatHistory, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.AiChatSessionEntity>> getChatSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getChatSessions, []),
            returnValue: _i9.Future<List<_i3.AiChatSessionEntity>>.value(
              <_i3.AiChatSessionEntity>[],
            ),
          )
          as _i9.Future<List<_i3.AiChatSessionEntity>>);

  @override
  _i9.Future<_i3.AiChatSessionEntity> createChatSession(
    String? title, {
    String? petId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChatSession, [title], {#petId: petId}),
            returnValue: _i9.Future<_i3.AiChatSessionEntity>.value(
              _FakeAiChatSessionEntity_1(
                this,
                Invocation.method(#createChatSession, [title], {#petId: petId}),
              ),
            ),
          )
          as _i9.Future<_i3.AiChatSessionEntity>);

  @override
  _i9.Future<void> deleteChatSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatSession, [sessionId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.AiSuggestedQuestionEntity>> getSuggestedQuestions() =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedQuestions, []),
            returnValue: _i9.Future<List<_i3.AiSuggestedQuestionEntity>>.value(
              <_i3.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i9.Future<List<_i3.AiSuggestedQuestionEntity>>);

  @override
  _i9.Future<List<_i3.AiSuggestedQuestionEntity>>
  getPersonalizedSuggestedQuestions({
    String? category,
    _i10.PetProfileEntity? pet,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonalizedSuggestedQuestions, [], {
              #category: category,
              #pet: pet,
            }),
            returnValue: _i9.Future<List<_i3.AiSuggestedQuestionEntity>>.value(
              <_i3.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i9.Future<List<_i3.AiSuggestedQuestionEntity>>);

  @override
  _i9.Future<_i3.AiFavoriteEntity> addFavoriteMessage(
    _i3.AiMessageEntity? message,
    String? category, {
    String? petId,
    String? petName,
    String? userNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addFavoriteMessage,
              [message, category],
              {#petId: petId, #petName: petName, #userNote: userNote},
            ),
            returnValue: _i9.Future<_i3.AiFavoriteEntity>.value(
              _FakeAiFavoriteEntity_2(
                this,
                Invocation.method(
                  #addFavoriteMessage,
                  [message, category],
                  {#petId: petId, #petName: petName, #userNote: userNote},
                ),
              ),
            ),
          )
          as _i9.Future<_i3.AiFavoriteEntity>);

  @override
  _i9.Future<void> removeFavoriteMessage(String? favoriteId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavoriteMessage, [favoriteId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.AiFavoriteEntity>> getFavoriteMessages({
    String? petId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteMessages, [], {
              #petId: petId,
              #category: category,
            }),
            returnValue: _i9.Future<List<_i3.AiFavoriteEntity>>.value(
              <_i3.AiFavoriteEntity>[],
            ),
          )
          as _i9.Future<List<_i3.AiFavoriteEntity>>);

  @override
  List<_i3.AiFavoriteQaEntity> getFavoriteQAs() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteQAs, []),
            returnValue: <_i3.AiFavoriteQaEntity>[],
          )
          as List<_i3.AiFavoriteQaEntity>);

  @override
  _i9.Future<_i3.AiChatSummaryEntity> createChatSummary(
    List<_i3.AiMessageEntity>? messages,
    String? category, {
    String? petId,
    String? petName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createChatSummary,
              [messages, category],
              {#petId: petId, #petName: petName},
            ),
            returnValue: _i9.Future<_i3.AiChatSummaryEntity>.value(
              _FakeAiChatSummaryEntity_3(
                this,
                Invocation.method(
                  #createChatSummary,
                  [messages, category],
                  {#petId: petId, #petName: petName},
                ),
              ),
            ),
          )
          as _i9.Future<_i3.AiChatSummaryEntity>);

  @override
  _i9.Future<List<_i3.AiChatSummaryEntity>> getChatSummaries({
    String? petId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatSummaries, [], {
              #petId: petId,
              #category: category,
            }),
            returnValue: _i9.Future<List<_i3.AiChatSummaryEntity>>.value(
              <_i3.AiChatSummaryEntity>[],
            ),
          )
          as _i9.Future<List<_i3.AiChatSummaryEntity>>);

  @override
  _i9.Future<void> deleteChatSummary(String? summaryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatSummary, [summaryId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> saveChatHistory(_i3.AiChatHistoryEntity? chatHistory) =>
      (super.noSuchMethod(
            Invocation.method(#saveChatHistory, [chatHistory]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.AiChatSummary> generateChatSummary({
    required List<String>? userMessages,
    required String? petName,
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateChatSummary, [], {
              #userMessages: userMessages,
              #petName: petName,
              #category: category,
            }),
            returnValue: _i9.Future<_i3.AiChatSummary>.value(
              _FakeAiChatSummary_4(
                this,
                Invocation.method(#generateChatSummary, [], {
                  #userMessages: userMessages,
                  #petName: petName,
                  #category: category,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.AiChatSummary>);

  @override
  _i9.Future<List<_i3.AiChatHistoryEntity>> getChatHistories({
    int? limit = 30,
    bool? onlyManualSaved = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistories, [], {
              #limit: limit,
              #onlyManualSaved: onlyManualSaved,
            }),
            returnValue: _i9.Future<List<_i3.AiChatHistoryEntity>>.value(
              <_i3.AiChatHistoryEntity>[],
            ),
          )
          as _i9.Future<List<_i3.AiChatHistoryEntity>>);

  @override
  _i9.Future<void> deleteChatHistory(String? historyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatHistory, [historyId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [OpenAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAIService extends _i1.Mock implements _i11.OpenAIService {
  MockOpenAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String> generateResponse(
    String? message, {
    _i10.PetProfileEntity? petContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateResponse,
              [message],
              {#petContext: petContext},
            ),
            returnValue: _i9.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(
                  #generateResponse,
                  [message],
                  {#petContext: petContext},
                ),
              ),
            ),
          )
          as _i9.Future<String>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i4.AuthResult> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i9.Future<_i4.AuthResult>.value(
              _FakeAuthResult_5(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i9.Future<_i4.AuthResult>);

  @override
  _i9.Future<_i4.AuthResult> createUserWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i9.Future<_i4.AuthResult>.value(
              _FakeAuthResult_5(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i9.Future<_i4.AuthResult>);

  @override
  _i9.Future<_i4.AuthResult> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i9.Future<_i4.AuthResult>.value(
              _FakeAuthResult_5(this, Invocation.method(#signInWithGoogle, [])),
            ),
          )
          as _i9.Future<_i4.AuthResult>);

  @override
  _i9.Future<_i4.AuthResult> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i9.Future<_i4.AuthResult>.value(
              _FakeAuthResult_5(this, Invocation.method(#signInWithApple, [])),
            ),
          )
          as _i9.Future<_i4.AuthResult>);

  @override
  _i9.Future<_i4.AuthResult> signInWithLine() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithLine, []),
            returnValue: _i9.Future<_i4.AuthResult>.value(
              _FakeAuthResult_5(this, Invocation.method(#signInWithLine, [])),
            ),
          )
          as _i9.Future<_i4.AuthResult>);

  @override
  _i9.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.AuthUser?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i9.Future<_i4.AuthUser?>.value(),
          )
          as _i9.Future<_i4.AuthUser?>);

  @override
  _i9.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateUserProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i13.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i5.HomeDashboardEntity> getDashboardData() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardData, []),
            returnValue: _i9.Future<_i5.HomeDashboardEntity>.value(
              _FakeHomeDashboardEntity_6(
                this,
                Invocation.method(#getDashboardData, []),
              ),
            ),
          )
          as _i9.Future<_i5.HomeDashboardEntity>);

  @override
  _i9.Future<_i5.WeatherEntity?> getCurrentWeather({
    _i5.WeatherLocationEntity? location,
    bool? userTriggered = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWeather, [], {
              #location: location,
              #userTriggered: userTriggered,
            }),
            returnValue: _i9.Future<_i5.WeatherEntity?>.value(),
          )
          as _i9.Future<_i5.WeatherEntity?>);

  @override
  _i9.Future<List<_i5.PetSummaryEntity>> getPetSummaries() =>
      (super.noSuchMethod(
            Invocation.method(#getPetSummaries, []),
            returnValue: _i9.Future<List<_i5.PetSummaryEntity>>.value(
              <_i5.PetSummaryEntity>[],
            ),
          )
          as _i9.Future<List<_i5.PetSummaryEntity>>);

  @override
  _i9.Future<_i5.WalkSummary> getWalkSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getWalkSummary, []),
            returnValue: _i9.Future<_i5.WalkSummary>.value(
              _FakeWalkSummary_7(this, Invocation.method(#getWalkSummary, [])),
            ),
          )
          as _i9.Future<_i5.WalkSummary>);

  @override
  _i9.Future<_i5.HealthSummary> getPetHealthSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getPetHealthSummary, []),
            returnValue: _i9.Future<_i5.HealthSummary>.value(
              _FakeHealthSummary_8(
                this,
                Invocation.method(#getPetHealthSummary, []),
              ),
            ),
          )
          as _i9.Future<_i5.HealthSummary>);

  @override
  _i9.Future<List<_i5.AppointmentSummary>> getUpcomingAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingAppointments, []),
            returnValue: _i9.Future<List<_i5.AppointmentSummary>>.value(
              <_i5.AppointmentSummary>[],
            ),
          )
          as _i9.Future<List<_i5.AppointmentSummary>>);
}

/// A class which mocks [PetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetRepository extends _i1.Mock implements _i10.PetRepository {
  MockPetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Result<List<_i10.PetProfileEntity>>> getAllPets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPets, []),
            returnValue:
                _i9.Future<_i2.Result<List<_i10.PetProfileEntity>>>.value(
                  _FakeResult_0<List<_i10.PetProfileEntity>>(
                    this,
                    Invocation.method(#getAllPets, []),
                  ),
                ),
          )
          as _i9.Future<_i2.Result<List<_i10.PetProfileEntity>>>);

  @override
  _i9.Future<_i2.Result<_i10.PetProfileEntity?>> getPetById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPetById, [id]),
            returnValue: _i9.Future<_i2.Result<_i10.PetProfileEntity?>>.value(
              _FakeResult_0<_i10.PetProfileEntity?>(
                this,
                Invocation.method(#getPetById, [id]),
              ),
            ),
          )
          as _i9.Future<_i2.Result<_i10.PetProfileEntity?>>);

  @override
  _i9.Future<_i2.Result<_i10.PetProfileEntity>> createPet(
    _i10.PetProfileEntity? pet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPet, [pet]),
            returnValue: _i9.Future<_i2.Result<_i10.PetProfileEntity>>.value(
              _FakeResult_0<_i10.PetProfileEntity>(
                this,
                Invocation.method(#createPet, [pet]),
              ),
            ),
          )
          as _i9.Future<_i2.Result<_i10.PetProfileEntity>>);

  @override
  _i9.Future<_i2.Result<_i10.PetProfileEntity>> updatePet(
    _i10.PetProfileEntity? pet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePet, [pet]),
            returnValue: _i9.Future<_i2.Result<_i10.PetProfileEntity>>.value(
              _FakeResult_0<_i10.PetProfileEntity>(
                this,
                Invocation.method(#updatePet, [pet]),
              ),
            ),
          )
          as _i9.Future<_i2.Result<_i10.PetProfileEntity>>);

  @override
  _i9.Future<_i2.Result<void>> deletePet(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePet, [id]),
            returnValue: _i9.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(this, Invocation.method(#deletePet, [id])),
            ),
          )
          as _i9.Future<_i2.Result<void>>);

  @override
  _i9.Future<void> saveTemporaryPetData(_i10.TemporaryPetDataEntity? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveTemporaryPetData, [data]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i10.TemporaryPetDataEntity?> getTemporaryPetData() =>
      (super.noSuchMethod(
            Invocation.method(#getTemporaryPetData, []),
            returnValue: _i9.Future<_i10.TemporaryPetDataEntity?>.value(),
          )
          as _i9.Future<_i10.TemporaryPetDataEntity?>);

  @override
  _i9.Future<void> clearTemporaryPetData() =>
      (super.noSuchMethod(
            Invocation.method(#clearTemporaryPetData, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [WalkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalkRepository extends _i1.Mock implements _i14.WalkRepository {
  MockWalkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i6.WalkRecordEntity>> getAllWalkRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWalkRecords, []),
            returnValue: _i9.Future<List<_i6.WalkRecordEntity>>.value(
              <_i6.WalkRecordEntity>[],
            ),
          )
          as _i9.Future<List<_i6.WalkRecordEntity>>);

  @override
  _i9.Future<List<_i6.WalkRecordEntity>> getWalkRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getWalkRecords, []),
            returnValue: _i9.Future<List<_i6.WalkRecordEntity>>.value(
              <_i6.WalkRecordEntity>[],
            ),
          )
          as _i9.Future<List<_i6.WalkRecordEntity>>);

  @override
  _i9.Future<_i6.WalkRecordEntity?> getWalkRecordById(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#getWalkRecordById, [recordId]),
            returnValue: _i9.Future<_i6.WalkRecordEntity?>.value(),
          )
          as _i9.Future<_i6.WalkRecordEntity?>);

  @override
  _i9.Future<List<_i6.WalkRecordEntity>> getWalkRecordsByPetId(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#getWalkRecordsByPetId, [petId]),
            returnValue: _i9.Future<List<_i6.WalkRecordEntity>>.value(
              <_i6.WalkRecordEntity>[],
            ),
          )
          as _i9.Future<List<_i6.WalkRecordEntity>>);

  @override
  _i9.Future<_i6.WalkRecordEntity?> getCurrentWalk() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWalk, []),
            returnValue: _i9.Future<_i6.WalkRecordEntity?>.value(),
          )
          as _i9.Future<_i6.WalkRecordEntity?>);

  @override
  _i9.Future<_i6.WalkRecordEntity> startWalk(
    _i6.WalkRecordEntity? walkRecord,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startWalk, [walkRecord]),
            returnValue: _i9.Future<_i6.WalkRecordEntity>.value(
              _FakeWalkRecordEntity_9(
                this,
                Invocation.method(#startWalk, [walkRecord]),
              ),
            ),
          )
          as _i9.Future<_i6.WalkRecordEntity>);

  @override
  _i9.Future<void> saveWalkRecord(_i6.WalkRecordEntity? walkRecord) =>
      (super.noSuchMethod(
            Invocation.method(#saveWalkRecord, [walkRecord]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateWalkRecord(_i6.WalkRecordEntity? walkRecord) =>
      (super.noSuchMethod(
            Invocation.method(#updateWalkRecord, [walkRecord]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteWalkRecord(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWalkRecord, [id]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i6.WalkRecordEntity> endWalk(
    String? recordId, {
    double? distance,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #endWalk,
              [recordId],
              {#distance: distance, #notes: notes},
            ),
            returnValue: _i9.Future<_i6.WalkRecordEntity>.value(
              _FakeWalkRecordEntity_9(
                this,
                Invocation.method(
                  #endWalk,
                  [recordId],
                  {#distance: distance, #notes: notes},
                ),
              ),
            ),
          )
          as _i9.Future<_i6.WalkRecordEntity>);

  @override
  _i9.Future<_i7.WalkStatistics> getWalkStatistics({
    String? petId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWalkStatistics, [], {
              #petId: petId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i9.Future<_i7.WalkStatistics>.value(
              _FakeWalkStatistics_10(
                this,
                Invocation.method(#getWalkStatistics, [], {
                  #petId: petId,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.WalkStatistics>);
}

/// A class which mocks [WalkRouteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalkRouteService extends _i1.Mock implements _i15.WalkRouteService {
  MockWalkRouteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double calculateTotalDistance(List<_i16.WalkLocation>? route) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTotalDistance, [route]),
            returnValue: 0.0,
          )
          as double);

  @override
  Duration calculateTotalDuration(List<_i16.WalkLocation>? route) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTotalDuration, [route]),
            returnValue: _FakeDuration_11(
              this,
              Invocation.method(#calculateTotalDuration, [route]),
            ),
          )
          as Duration);

  @override
  double calculateAverageSpeed(List<_i16.WalkLocation>? route) =>
      (super.noSuchMethod(
            Invocation.method(#calculateAverageSpeed, [route]),
            returnValue: 0.0,
          )
          as double);

  @override
  String encodePolyline(List<_i16.WalkLocation>? route) =>
      (super.noSuchMethod(
            Invocation.method(#encodePolyline, [route]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#encodePolyline, [route]),
            ),
          )
          as String);

  @override
  List<_i16.WalkLocation> decodePolyline(String? encodedPolyline) =>
      (super.noSuchMethod(
            Invocation.method(#decodePolyline, [encodedPolyline]),
            returnValue: <_i16.WalkLocation>[],
          )
          as List<_i16.WalkLocation>);

  @override
  List<_i16.WalkLocation> optimizeRoute(List<_i16.WalkLocation>? route) =>
      (super.noSuchMethod(
            Invocation.method(#optimizeRoute, [route]),
            returnValue: <_i16.WalkLocation>[],
          )
          as List<_i16.WalkLocation>);

  @override
  List<_i16.WalkLocation> smoothRoute(List<_i16.WalkLocation>? route) =>
      (super.noSuchMethod(
            Invocation.method(#smoothRoute, [route]),
            returnValue: <_i16.WalkLocation>[],
          )
          as List<_i16.WalkLocation>);
}

/// A class which mocks [ValidationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidationService extends _i1.Mock implements _i2.ValidationService {
  MockValidationService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [CommonErrorService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommonErrorService extends _i1.Mock
    implements _i2.CommonErrorService {
  MockCommonErrorService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Stream<_i2.ErrorInfo> get errorStream =>
      (super.noSuchMethod(
            Invocation.getter(#errorStream),
            returnValue: _i9.Stream<_i2.ErrorInfo>.empty(),
          )
          as _i9.Stream<_i2.ErrorInfo>);

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> handleErrorInstance(
    dynamic error, {
    String? message,
    _i2.ErrorSeverity? severity = _i2.ErrorSeverity.medium,
    _i2.ErrorType? type = _i2.ErrorType.unknown,
    Map<String, dynamic>? context,
    StackTrace? stackTrace,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #handleErrorInstance,
              [error],
              {
                #message: message,
                #severity: severity,
                #type: type,
                #context: context,
                #stackTrace: stackTrace,
              },
            ),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  Map<String, dynamic> getErrorStats() =>
      (super.noSuchMethod(
            Invocation.method(#getErrorStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  List<_i2.ErrorInfo> getErrorHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getErrorHistory, []),
            returnValue: <_i2.ErrorInfo>[],
          )
          as List<_i2.ErrorInfo>);

  @override
  int getErrorCountByType(_i2.ErrorType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getErrorCountByType, [type]),
            returnValue: 0,
          )
          as int);

  @override
  int getErrorCountBySeverity(_i2.ErrorSeverity? severity) =>
      (super.noSuchMethod(
            Invocation.method(#getErrorCountBySeverity, [severity]),
            returnValue: 0,
          )
          as int);

  @override
  void setEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void clearErrorHistory() => super.noSuchMethod(
    Invocation.method(#clearErrorHistory, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUiService extends _i1.Mock implements _i2.UiService {
  MockUiService() {
    _i1.throwOnMissingStub(this);
  }
}
