// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/shared_mockito_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:aipet_frontend/features/ai/domain/entities/entities.dart'
    as _i2;
import 'package:aipet_frontend/features/ai/domain/repositories/ai_repository.dart'
    as _i5;
import 'package:aipet_frontend/features/auth/domain/repositories/auth_repository.dart'
    as _i10;
import 'package:aipet_frontend/features/home/domain/entities/entities.dart'
    as _i3;
import 'package:aipet_frontend/features/home/domain/repositories/home_repository.dart'
    as _i11;
import 'package:aipet_frontend/features/pet_registor/domain/entities/temporary_pet_data_entity.dart'
    as _i13;
import 'package:aipet_frontend/features/pet_registor/domain/repositories/pet_repository.dart'
    as _i12;
import 'package:aipet_frontend/shared/core/services/http_client_service.dart'
    as _i14;
import 'package:aipet_frontend/shared/domain/entities/entities.dart' as _i9;
import 'package:aipet_frontend/shared/foundation/result/app_result.dart' as _i7;
import 'package:aipet_frontend/shared/shared.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAiChatSessionEntity_0 extends _i1.SmartFake
    implements _i2.AiChatSessionEntity {
  _FakeAiChatSessionEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiFavoriteEntity_1 extends _i1.SmartFake
    implements _i2.AiFavoriteEntity {
  _FakeAiFavoriteEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSummaryEntity_2 extends _i1.SmartFake
    implements _i2.AiChatSummaryEntity {
  _FakeAiChatSummaryEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSummary_3 extends _i1.SmartFake implements _i2.AiChatSummary {
  _FakeAiChatSummary_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeDashboardEntity_4 extends _i1.SmartFake
    implements _i3.HomeDashboardEntity {
  _FakeHomeDashboardEntity_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalkSummary_5 extends _i1.SmartFake implements _i3.WalkSummary {
  _FakeWalkSummary_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthSummary_6 extends _i1.SmartFake implements _i3.HealthSummary {
  _FakeHealthSummary_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiResponse_7<T1> extends _i1.SmartFake
    implements _i4.ApiResponse<T1> {
  _FakeApiResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiRepository extends _i1.Mock implements _i5.AiRepository {
  MockAiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.AiMessageEntity>> getChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistory, []),
            returnValue: _i6.Future<List<_i2.AiMessageEntity>>.value(
              <_i2.AiMessageEntity>[],
            ),
          )
          as _i6.Future<List<_i2.AiMessageEntity>>);

  @override
  _i6.Future<_i7.Result<_i2.AiMessageEntity>> sendMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i6.Future<_i7.Result<_i2.AiMessageEntity>>.value(
              _i8.dummyValue<_i7.Result<_i2.AiMessageEntity>>(
                this,
                Invocation.method(#sendMessage, [message]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i2.AiMessageEntity>>);

  @override
  _i6.Future<_i7.Result<_i2.AiMessageEntity>> sendMessageWithPetContext(
    String? message, {
    _i9.PetProfileEntity? petContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessageWithPetContext,
              [message],
              {#petContext: petContext},
            ),
            returnValue: _i6.Future<_i7.Result<_i2.AiMessageEntity>>.value(
              _i8.dummyValue<_i7.Result<_i2.AiMessageEntity>>(
                this,
                Invocation.method(
                  #sendMessageWithPetContext,
                  [message],
                  {#petContext: petContext},
                ),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i2.AiMessageEntity>>);

  @override
  _i6.Future<void> clearChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearChatHistory, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.AiChatSessionEntity>> getChatSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getChatSessions, []),
            returnValue: _i6.Future<List<_i2.AiChatSessionEntity>>.value(
              <_i2.AiChatSessionEntity>[],
            ),
          )
          as _i6.Future<List<_i2.AiChatSessionEntity>>);

  @override
  _i6.Future<_i2.AiChatSessionEntity> createChatSession(
    String? title, {
    String? petId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChatSession, [title], {#petId: petId}),
            returnValue: _i6.Future<_i2.AiChatSessionEntity>.value(
              _FakeAiChatSessionEntity_0(
                this,
                Invocation.method(#createChatSession, [title], {#petId: petId}),
              ),
            ),
          )
          as _i6.Future<_i2.AiChatSessionEntity>);

  @override
  _i6.Future<void> deleteChatSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatSession, [sessionId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.AiSuggestedQuestionEntity>> getSuggestedQuestions() =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedQuestions, []),
            returnValue: _i6.Future<List<_i2.AiSuggestedQuestionEntity>>.value(
              <_i2.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i6.Future<List<_i2.AiSuggestedQuestionEntity>>);

  @override
  _i6.Future<List<_i2.AiSuggestedQuestionEntity>>
  getPersonalizedSuggestedQuestions({
    String? category,
    _i9.PetProfileEntity? pet,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonalizedSuggestedQuestions, [], {
              #category: category,
              #pet: pet,
            }),
            returnValue: _i6.Future<List<_i2.AiSuggestedQuestionEntity>>.value(
              <_i2.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i6.Future<List<_i2.AiSuggestedQuestionEntity>>);

  @override
  _i6.Future<_i2.AiFavoriteEntity> addFavoriteMessage(
    _i2.AiMessageEntity? message,
    String? category, {
    String? petId,
    String? petName,
    String? userNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addFavoriteMessage,
              [message, category],
              {#petId: petId, #petName: petName, #userNote: userNote},
            ),
            returnValue: _i6.Future<_i2.AiFavoriteEntity>.value(
              _FakeAiFavoriteEntity_1(
                this,
                Invocation.method(
                  #addFavoriteMessage,
                  [message, category],
                  {#petId: petId, #petName: petName, #userNote: userNote},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.AiFavoriteEntity>);

  @override
  _i6.Future<void> removeFavoriteMessage(String? favoriteId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavoriteMessage, [favoriteId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i2.AiFavoriteEntity>> getFavoriteMessages({
    String? petId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteMessages, [], {
              #petId: petId,
              #category: category,
            }),
            returnValue: _i6.Future<List<_i2.AiFavoriteEntity>>.value(
              <_i2.AiFavoriteEntity>[],
            ),
          )
          as _i6.Future<List<_i2.AiFavoriteEntity>>);

  @override
  List<_i2.AiFavoriteQaEntity> getFavoriteQAs() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteQAs, []),
            returnValue: <_i2.AiFavoriteQaEntity>[],
          )
          as List<_i2.AiFavoriteQaEntity>);

  @override
  _i6.Future<_i2.AiChatSummaryEntity> createChatSummary(
    List<_i2.AiMessageEntity>? messages,
    String? category, {
    String? petId,
    String? petName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createChatSummary,
              [messages, category],
              {#petId: petId, #petName: petName},
            ),
            returnValue: _i6.Future<_i2.AiChatSummaryEntity>.value(
              _FakeAiChatSummaryEntity_2(
                this,
                Invocation.method(
                  #createChatSummary,
                  [messages, category],
                  {#petId: petId, #petName: petName},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.AiChatSummaryEntity>);

  @override
  _i6.Future<List<_i2.AiChatSummaryEntity>> getChatSummaries({
    String? petId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatSummaries, [], {
              #petId: petId,
              #category: category,
            }),
            returnValue: _i6.Future<List<_i2.AiChatSummaryEntity>>.value(
              <_i2.AiChatSummaryEntity>[],
            ),
          )
          as _i6.Future<List<_i2.AiChatSummaryEntity>>);

  @override
  _i6.Future<void> deleteChatSummary(String? summaryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatSummary, [summaryId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveChatHistory(_i2.AiChatHistoryEntity? chatHistory) =>
      (super.noSuchMethod(
            Invocation.method(#saveChatHistory, [chatHistory]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.AiChatSummary> generateChatSummary({
    required List<String>? userMessages,
    required String? petName,
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateChatSummary, [], {
              #userMessages: userMessages,
              #petName: petName,
              #category: category,
            }),
            returnValue: _i6.Future<_i2.AiChatSummary>.value(
              _FakeAiChatSummary_3(
                this,
                Invocation.method(#generateChatSummary, [], {
                  #userMessages: userMessages,
                  #petName: petName,
                  #category: category,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.AiChatSummary>);

  @override
  _i6.Future<List<_i2.AiChatHistoryEntity>> getChatHistories({
    int? limit = 30,
    bool? onlyManualSaved = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistories, [], {
              #limit: limit,
              #onlyManualSaved: onlyManualSaved,
            }),
            returnValue: _i6.Future<List<_i2.AiChatHistoryEntity>>.value(
              <_i2.AiChatHistoryEntity>[],
            ),
          )
          as _i6.Future<List<_i2.AiChatHistoryEntity>>);

  @override
  _i6.Future<void> deleteChatHistory(String? historyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatHistory, [historyId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i7.Result<List<_i2.AiMessageEntity>>> loadChatHistory({
    required String? userId,
    String? petId,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadChatHistory, [], {
              #userId: userId,
              #petId: petId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue:
                _i6.Future<_i7.Result<List<_i2.AiMessageEntity>>>.value(
                  _i8.dummyValue<_i7.Result<List<_i2.AiMessageEntity>>>(
                    this,
                    Invocation.method(#loadChatHistory, [], {
                      #userId: userId,
                      #petId: petId,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<List<_i2.AiMessageEntity>>>);

  @override
  _i6.Future<_i7.Result<_i2.AiAnalysisEntity>> analyzeMessage({
    required String? message,
    String? petId,
    Map<String, dynamic>? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeMessage, [], {
              #message: message,
              #petId: petId,
              #context: context,
            }),
            returnValue: _i6.Future<_i7.Result<_i2.AiAnalysisEntity>>.value(
              _i8.dummyValue<_i7.Result<_i2.AiAnalysisEntity>>(
                this,
                Invocation.method(#analyzeMessage, [], {
                  #message: message,
                  #petId: petId,
                  #context: context,
                }),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i2.AiAnalysisEntity>>);

  @override
  _i6.Future<_i7.Result<_i2.AiMessageEntity>> sendMessageWithParams({
    required String? message,
    required String? petId,
    String? categoryId,
    List<String>? attachedImages,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessageWithParams, [], {
              #message: message,
              #petId: petId,
              #categoryId: categoryId,
              #attachedImages: attachedImages,
            }),
            returnValue: _i6.Future<_i7.Result<_i2.AiMessageEntity>>.value(
              _i8.dummyValue<_i7.Result<_i2.AiMessageEntity>>(
                this,
                Invocation.method(#sendMessageWithParams, [], {
                  #message: message,
                  #petId: petId,
                  #categoryId: categoryId,
                  #attachedImages: attachedImages,
                }),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i2.AiMessageEntity>>);

  @override
  _i6.Future<_i7.Result<bool>> toggleFavoriteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavoriteMessage, [messageId]),
            returnValue: _i6.Future<_i7.Result<bool>>.value(
              _i8.dummyValue<_i7.Result<bool>>(
                this,
                Invocation.method(#toggleFavoriteMessage, [messageId]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<bool>>);

  @override
  _i6.Future<_i7.Result<List<_i2.AiSuggestedQuestionEntity>>>
  getSuggestedQuestionsWithParams({String? petId, String? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedQuestionsWithParams, [], {
              #petId: petId,
              #categoryId: categoryId,
            }),
            returnValue:
                _i6.Future<
                  _i7.Result<List<_i2.AiSuggestedQuestionEntity>>
                >.value(
                  _i8.dummyValue<
                    _i7.Result<List<_i2.AiSuggestedQuestionEntity>>
                  >(
                    this,
                    Invocation.method(#getSuggestedQuestionsWithParams, [], {
                      #petId: petId,
                      #categoryId: categoryId,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<List<_i2.AiSuggestedQuestionEntity>>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i10.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Result<_i10.AuthUser>> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i6.Future<_i7.Result<_i10.AuthUser>>.value(
              _i8.dummyValue<_i7.Result<_i10.AuthUser>>(
                this,
                Invocation.method(#signInWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i10.AuthUser>>);

  @override
  _i6.Future<_i7.Result<_i10.AuthUser>> createUserWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i6.Future<_i7.Result<_i10.AuthUser>>.value(
              _i8.dummyValue<_i7.Result<_i10.AuthUser>>(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i10.AuthUser>>);

  @override
  _i6.Future<_i7.Result<_i10.AuthUser>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i6.Future<_i7.Result<_i10.AuthUser>>.value(
              _i8.dummyValue<_i7.Result<_i10.AuthUser>>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i10.AuthUser>>);

  @override
  _i6.Future<_i7.Result<_i10.AuthUser>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i6.Future<_i7.Result<_i10.AuthUser>>.value(
              _i8.dummyValue<_i7.Result<_i10.AuthUser>>(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i10.AuthUser>>);

  @override
  _i6.Future<_i7.Result<_i10.AuthUser>> signInWithLine() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithLine, []),
            returnValue: _i6.Future<_i7.Result<_i10.AuthUser>>.value(
              _i8.dummyValue<_i7.Result<_i10.AuthUser>>(
                this,
                Invocation.method(#signInWithLine, []),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i10.AuthUser>>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i10.AuthUser?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i6.Future<_i10.AuthUser?>.value(),
          )
          as _i6.Future<_i10.AuthUser?>);

  @override
  _i6.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> exchangeServerToken(String? idToken) =>
      (super.noSuchMethod(
            Invocation.method(#exchangeServerToken, [idToken]),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#exchangeServerToken, [idToken]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String?> getCurrentUserIdToken() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserIdToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> getStoredServerToken() =>
      (super.noSuchMethod(
            Invocation.method(#getStoredServerToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> saveServerToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveServerToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearServerToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearServerToken, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i11.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.HomeDashboardEntity> getDashboardData() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardData, []),
            returnValue: _i6.Future<_i3.HomeDashboardEntity>.value(
              _FakeHomeDashboardEntity_4(
                this,
                Invocation.method(#getDashboardData, []),
              ),
            ),
          )
          as _i6.Future<_i3.HomeDashboardEntity>);

  @override
  _i6.Future<_i3.WeatherEntity?> getCurrentWeather({
    _i3.WeatherLocationEntity? location,
    bool? userTriggered = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWeather, [], {
              #location: location,
              #userTriggered: userTriggered,
            }),
            returnValue: _i6.Future<_i3.WeatherEntity?>.value(),
          )
          as _i6.Future<_i3.WeatherEntity?>);

  @override
  _i6.Future<List<_i3.PetSummaryEntity>> getPetSummaries() =>
      (super.noSuchMethod(
            Invocation.method(#getPetSummaries, []),
            returnValue: _i6.Future<List<_i3.PetSummaryEntity>>.value(
              <_i3.PetSummaryEntity>[],
            ),
          )
          as _i6.Future<List<_i3.PetSummaryEntity>>);

  @override
  _i6.Future<_i3.WalkSummary> getWalkSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getWalkSummary, []),
            returnValue: _i6.Future<_i3.WalkSummary>.value(
              _FakeWalkSummary_5(this, Invocation.method(#getWalkSummary, [])),
            ),
          )
          as _i6.Future<_i3.WalkSummary>);

  @override
  _i6.Future<_i3.HealthSummary> getPetHealthSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getPetHealthSummary, []),
            returnValue: _i6.Future<_i3.HealthSummary>.value(
              _FakeHealthSummary_6(
                this,
                Invocation.method(#getPetHealthSummary, []),
              ),
            ),
          )
          as _i6.Future<_i3.HealthSummary>);

  @override
  _i6.Future<List<_i3.AppointmentSummary>> getUpcomingAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingAppointments, []),
            returnValue: _i6.Future<List<_i3.AppointmentSummary>>.value(
              <_i3.AppointmentSummary>[],
            ),
          )
          as _i6.Future<List<_i3.AppointmentSummary>>);
}

/// A class which mocks [PetRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetRepository extends _i1.Mock implements _i12.PetRepository {
  MockPetRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Result<List<_i9.PetProfileEntity>>> getAllPets() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPets, []),
            returnValue:
                _i6.Future<_i7.Result<List<_i9.PetProfileEntity>>>.value(
                  _i8.dummyValue<_i7.Result<List<_i9.PetProfileEntity>>>(
                    this,
                    Invocation.method(#getAllPets, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Result<List<_i9.PetProfileEntity>>>);

  @override
  _i6.Future<_i7.Result<_i9.PetProfileEntity?>> getPetById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPetById, [id]),
            returnValue: _i6.Future<_i7.Result<_i9.PetProfileEntity?>>.value(
              _i8.dummyValue<_i7.Result<_i9.PetProfileEntity?>>(
                this,
                Invocation.method(#getPetById, [id]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i9.PetProfileEntity?>>);

  @override
  _i6.Future<_i7.Result<_i9.PetProfileEntity>> createPet(
    _i9.PetProfileEntity? pet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPet, [pet]),
            returnValue: _i6.Future<_i7.Result<_i9.PetProfileEntity>>.value(
              _i8.dummyValue<_i7.Result<_i9.PetProfileEntity>>(
                this,
                Invocation.method(#createPet, [pet]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i9.PetProfileEntity>>);

  @override
  _i6.Future<_i7.Result<_i9.PetProfileEntity>> updatePet(
    _i9.PetProfileEntity? pet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePet, [pet]),
            returnValue: _i6.Future<_i7.Result<_i9.PetProfileEntity>>.value(
              _i8.dummyValue<_i7.Result<_i9.PetProfileEntity>>(
                this,
                Invocation.method(#updatePet, [pet]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<_i9.PetProfileEntity>>);

  @override
  _i6.Future<_i7.Result<void>> deletePet(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deletePet, [id]),
            returnValue: _i6.Future<_i7.Result<void>>.value(
              _i8.dummyValue<_i7.Result<void>>(
                this,
                Invocation.method(#deletePet, [id]),
              ),
            ),
          )
          as _i6.Future<_i7.Result<void>>);

  @override
  _i6.Future<void> saveTemporaryPetData(_i13.TemporaryPetDataEntity? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveTemporaryPetData, [data]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i13.TemporaryPetDataEntity?> getTemporaryPetData() =>
      (super.noSuchMethod(
            Invocation.method(#getTemporaryPetData, []),
            returnValue: _i6.Future<_i13.TemporaryPetDataEntity?>.value(),
          )
          as _i6.Future<_i13.TemporaryPetDataEntity?>);

  @override
  _i6.Future<void> clearTemporaryPetData() =>
      (super.noSuchMethod(
            Invocation.method(#clearTemporaryPetData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [HttpClientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClientService extends _i1.Mock implements _i14.HttpClientService {
  MockHttpClientService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.ApiResponse<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters, #fromJson: fromJson},
            ),
            returnValue: _i6.Future<_i4.ApiResponse<T>>.value(
              _FakeApiResponse_7<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters, #fromJson: fromJson},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.ApiResponse<T>>);

  @override
  _i6.Future<_i4.ApiResponse<T>> post<T>(
    String? path, {
    Map<String, dynamic>? data,
    T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {#data: data, #fromJson: fromJson},
            ),
            returnValue: _i6.Future<_i4.ApiResponse<T>>.value(
              _FakeApiResponse_7<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {#data: data, #fromJson: fromJson},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.ApiResponse<T>>);

  @override
  _i6.Future<_i4.ApiResponse<T>> put<T>(
    String? path, {
    Map<String, dynamic>? data,
    T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path], {#data: data, #fromJson: fromJson}),
            returnValue: _i6.Future<_i4.ApiResponse<T>>.value(
              _FakeApiResponse_7<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {#data: data, #fromJson: fromJson},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.ApiResponse<T>>);

  @override
  _i6.Future<_i4.ApiResponse<T>> delete<T>(
    String? path, {
    T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path], {#fromJson: fromJson}),
            returnValue: _i6.Future<_i4.ApiResponse<T>>.value(
              _FakeApiResponse_7<T>(
                this,
                Invocation.method(#delete, [path], {#fromJson: fromJson}),
              ),
            ),
          )
          as _i6.Future<_i4.ApiResponse<T>>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i4.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }
}
