// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/unit/features/ai/data/services/openai_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aipet_frontend/features/ai/data/services/pet_content_filter_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePetContentValidationResult_0 extends _i1.SmartFake
    implements _i2.PetContentValidationResult {
  _FakePetContentValidationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PetContentFilterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPetContentFilterService extends _i1.Mock
    implements _i2.PetContentFilterService {
  MockPetContentFilterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.PetContentValidationResult> validatePetContent(
    String? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validatePetContent, [message]),
            returnValue: _i3.Future<_i2.PetContentValidationResult>.value(
              _FakePetContentValidationResult_0(
                this,
                Invocation.method(#validatePetContent, [message]),
              ),
            ),
          )
          as _i3.Future<_i2.PetContentValidationResult>);

  @override
  _i3.Future<bool> isPetRelated(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#isPetRelated, [message]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
