name: aipet_frontend
description: "AI Pet Management App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  google_fonts: ^6.3.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.6.2
  shared_preferences: ^2.2.2
  webview_flutter: ^4.8.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.3
  fl_chart: ^0.68.0
  http: ^1.2.2
  path_provider: ^2.1.4
  crypto: ^3.0.3
  flutter_local_notifications: ^17.2.3
  url_launcher: ^6.2.4
  share_plus: ^7.2.1
  qr_code_scanner: ^1.0.1
  permission_handler: ^11.3.1
  flutter_secure_storage: ^9.2.2
  dio: ^5.4.3+1
  package_info_plus: ^8.0.2
  connectivity_plus: ^6.0.5

  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.13
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/meteocons/
    - assets/meteocons/design/fill/animation-ready/
    - assets/meteocons/viewer.html
    - assets/meteocons/viewer.html
    - assets/images/
    - assets/images/activities/
    - assets/images/backgrounds/
    - assets/images/cats/
    - assets/images/dogs/
    - assets/images/onboarding/
    - assets/images/etc/
    - assets/images/medications/
    - assets/images/textures/
    - assets/images/walks/
    - assets/icons/
    - assets/icons/navigation/
    - assets/icons/weathers/
    - assets/fonts/
    - assets/lottie/
