// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/unit/features/ai/presentation/controllers/ai_chat_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:aipet_frontend/features/ai/domain/entities/entities.dart'
    as _i3;
import 'package:aipet_frontend/features/ai/domain/repositories/ai_repository.dart'
    as _i4;
import 'package:aipet_frontend/features/pet_registor/pet_registor.dart' as _i6;
import 'package:aipet_frontend/shared/shared.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSessionEntity_1 extends _i1.SmartFake
    implements _i3.AiChatSessionEntity {
  _FakeAiChatSessionEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiFavoriteEntity_2 extends _i1.SmartFake
    implements _i3.AiFavoriteEntity {
  _FakeAiFavoriteEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSummaryEntity_3 extends _i1.SmartFake
    implements _i3.AiChatSummaryEntity {
  _FakeAiChatSummaryEntity_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiChatSummary_4 extends _i1.SmartFake implements _i3.AiChatSummary {
  _FakeAiChatSummary_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiRepository extends _i1.Mock implements _i4.AiRepository {
  MockAiRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.AiMessageEntity>> getChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistory, []),
            returnValue: _i5.Future<List<_i3.AiMessageEntity>>.value(
              <_i3.AiMessageEntity>[],
            ),
          )
          as _i5.Future<List<_i3.AiMessageEntity>>);

  @override
  _i5.Future<_i2.Result<_i3.AiMessageEntity>> sendMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i5.Future<_i2.Result<_i3.AiMessageEntity>>.value(
              _FakeResult_0<_i3.AiMessageEntity>(
                this,
                Invocation.method(#sendMessage, [message]),
              ),
            ),
          )
          as _i5.Future<_i2.Result<_i3.AiMessageEntity>>);

  @override
  _i5.Future<_i2.Result<_i3.AiMessageEntity>> sendMessageWithPetContext(
    String? message, {
    _i6.PetProfileEntity? petContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessageWithPetContext,
              [message],
              {#petContext: petContext},
            ),
            returnValue: _i5.Future<_i2.Result<_i3.AiMessageEntity>>.value(
              _FakeResult_0<_i3.AiMessageEntity>(
                this,
                Invocation.method(
                  #sendMessageWithPetContext,
                  [message],
                  {#petContext: petContext},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Result<_i3.AiMessageEntity>>);

  @override
  _i5.Future<void> clearChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearChatHistory, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.AiChatSessionEntity>> getChatSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getChatSessions, []),
            returnValue: _i5.Future<List<_i3.AiChatSessionEntity>>.value(
              <_i3.AiChatSessionEntity>[],
            ),
          )
          as _i5.Future<List<_i3.AiChatSessionEntity>>);

  @override
  _i5.Future<_i3.AiChatSessionEntity> createChatSession(
    String? title, {
    String? petId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChatSession, [title], {#petId: petId}),
            returnValue: _i5.Future<_i3.AiChatSessionEntity>.value(
              _FakeAiChatSessionEntity_1(
                this,
                Invocation.method(#createChatSession, [title], {#petId: petId}),
              ),
            ),
          )
          as _i5.Future<_i3.AiChatSessionEntity>);

  @override
  _i5.Future<void> deleteChatSession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatSession, [sessionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.AiSuggestedQuestionEntity>> getSuggestedQuestions() =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedQuestions, []),
            returnValue: _i5.Future<List<_i3.AiSuggestedQuestionEntity>>.value(
              <_i3.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i5.Future<List<_i3.AiSuggestedQuestionEntity>>);

  @override
  _i5.Future<List<_i3.AiSuggestedQuestionEntity>>
  getPersonalizedSuggestedQuestions({
    String? category,
    _i6.PetProfileEntity? pet,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonalizedSuggestedQuestions, [], {
              #category: category,
              #pet: pet,
            }),
            returnValue: _i5.Future<List<_i3.AiSuggestedQuestionEntity>>.value(
              <_i3.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i5.Future<List<_i3.AiSuggestedQuestionEntity>>);

  @override
  _i5.Future<_i3.AiFavoriteEntity> addFavoriteMessage(
    _i3.AiMessageEntity? message,
    String? category, {
    String? petId,
    String? petName,
    String? userNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addFavoriteMessage,
              [message, category],
              {#petId: petId, #petName: petName, #userNote: userNote},
            ),
            returnValue: _i5.Future<_i3.AiFavoriteEntity>.value(
              _FakeAiFavoriteEntity_2(
                this,
                Invocation.method(
                  #addFavoriteMessage,
                  [message, category],
                  {#petId: petId, #petName: petName, #userNote: userNote},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.AiFavoriteEntity>);

  @override
  _i5.Future<void> removeFavoriteMessage(String? favoriteId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFavoriteMessage, [favoriteId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.AiFavoriteEntity>> getFavoriteMessages({
    String? petId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteMessages, [], {
              #petId: petId,
              #category: category,
            }),
            returnValue: _i5.Future<List<_i3.AiFavoriteEntity>>.value(
              <_i3.AiFavoriteEntity>[],
            ),
          )
          as _i5.Future<List<_i3.AiFavoriteEntity>>);

  @override
  List<_i3.AiFavoriteQaEntity> getFavoriteQAs() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteQAs, []),
            returnValue: <_i3.AiFavoriteQaEntity>[],
          )
          as List<_i3.AiFavoriteQaEntity>);

  @override
  _i5.Future<_i3.AiChatSummaryEntity> createChatSummary(
    List<_i3.AiMessageEntity>? messages,
    String? category, {
    String? petId,
    String? petName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createChatSummary,
              [messages, category],
              {#petId: petId, #petName: petName},
            ),
            returnValue: _i5.Future<_i3.AiChatSummaryEntity>.value(
              _FakeAiChatSummaryEntity_3(
                this,
                Invocation.method(
                  #createChatSummary,
                  [messages, category],
                  {#petId: petId, #petName: petName},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.AiChatSummaryEntity>);

  @override
  _i5.Future<List<_i3.AiChatSummaryEntity>> getChatSummaries({
    String? petId,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatSummaries, [], {
              #petId: petId,
              #category: category,
            }),
            returnValue: _i5.Future<List<_i3.AiChatSummaryEntity>>.value(
              <_i3.AiChatSummaryEntity>[],
            ),
          )
          as _i5.Future<List<_i3.AiChatSummaryEntity>>);

  @override
  _i5.Future<void> deleteChatSummary(String? summaryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatSummary, [summaryId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveChatHistory(_i3.AiChatHistoryEntity? chatHistory) =>
      (super.noSuchMethod(
            Invocation.method(#saveChatHistory, [chatHistory]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.AiChatSummary> generateChatSummary({
    required List<String>? userMessages,
    required String? petName,
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateChatSummary, [], {
              #userMessages: userMessages,
              #petName: petName,
              #category: category,
            }),
            returnValue: _i5.Future<_i3.AiChatSummary>.value(
              _FakeAiChatSummary_4(
                this,
                Invocation.method(#generateChatSummary, [], {
                  #userMessages: userMessages,
                  #petName: petName,
                  #category: category,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AiChatSummary>);

  @override
  _i5.Future<List<_i3.AiChatHistoryEntity>> getChatHistories({
    int? limit = 30,
    bool? onlyManualSaved = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistories, [], {
              #limit: limit,
              #onlyManualSaved: onlyManualSaved,
            }),
            returnValue: _i5.Future<List<_i3.AiChatHistoryEntity>>.value(
              <_i3.AiChatHistoryEntity>[],
            ),
          )
          as _i5.Future<List<_i3.AiChatHistoryEntity>>);

  @override
  _i5.Future<void> deleteChatHistory(String? historyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChatHistory, [historyId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
