#!/bin/bash

# Firebase ID Token 취득 가이드

echo "🔑 Firebase ID Token 취득 가이드"
echo ""
echo "============================================================"
echo ""
echo "이 스크립트는 Flutter 앱을 통해 토큰을 확인하는 방법을 안내합니다."
echo ""
echo "단계 1: Flutter 앱 실행"
echo "  \$ flutter run"
echo ""
echo "단계 2: 앱에서 로그인"
echo "  - Firebase 인증으로 로그인"
echo ""
echo "단계 3: API 테스트 화면으로 이동"
echo "  - Settings → 開発者ツール → バックエンドAPI テスト"
echo ""
echo "단계 4: 토큰 복사"
echo "  1. 「Firebase 認証状態確認」 버튼 탭"
echo "  2. 「トークンをクリップボードにコピー」 버튼 탭"
echo ""
echo "단계 5: 토큰 사용"
echo "  - 클립보드에 복사된 토큰을 사용"
echo "  - curl 예시:"
echo "    \$ curl -H \"Authorization: Bearer YOUR_TOKEN\" \\"
echo "           http://localhost:3000/api/pets"
echo ""
echo "============================================================"
echo ""
echo "💡 Tip: API 테스트 화면에서 「全テスト実行」 버튼으로"
echo "   모든 API를 한 번에 테스트할 수 있습니다!"
echo ""
echo "📱 지원되는 플랫폼:"
echo "  - Android (에뮬레이터 또는 실제 기기)"
echo "  - iOS (시뮬레이터 또는 실제 기기)"
echo ""
