// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMGGVKpekvx7hIglGOEix69EoIG9JIQrI',
    appId: '1:916090550504:web:0a887fc627a77acbaf715d',
    messagingSenderId: '916090550504',
    projectId: 'aipet-1c44e',
    authDomain: 'aipet-1c44e.firebaseapp.com',
    databaseURL: 'https://aipet-1c44e-default-rtdb.firebaseio.com',
    storageBucket: 'aipet-1c44e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_hnnc4cBx8QI0662vscDwlJHeLNsoA2c',
    appId: '1:916090550504:android:c8690251473cd186af715d',
    messagingSenderId: '916090550504',
    projectId: 'aipet-1c44e',
    authDomain: 'aipet-1c44e.firebaseapp.com',
    databaseURL: 'https://aipet-1c44e-default-rtdb.firebaseio.com',
    storageBucket: 'aipet-1c44e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMGGVKpekvx7hIglGOEix69EoIG9JIQrI',
    appId: '1:916090550504:ios:0a887fc627a77acbaf715d',
    messagingSenderId: '916090550504',
    projectId: 'aipet-1c44e',
    authDomain: 'aipet-1c44e.firebaseapp.com',
    databaseURL: 'https://aipet-1c44e-default-rtdb.firebaseio.com',
    storageBucket: 'aipet-1c44e.firebasestorage.app',
    iosBundleId: 'com.itz.aipet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMGGVKpekvx7hIglGOEix69EoIG9JIQrI',
    appId: '1:916090550504:ios:0a887fc627a77acbaf715d',
    messagingSenderId: '916090550504',
    projectId: 'aipet-1c44e',
    authDomain: 'aipet-1c44e.firebaseapp.com',
    databaseURL: 'https://aipet-1c44e-default-rtdb.firebaseio.com',
    storageBucket: 'aipet-1c44e.firebasestorage.app',
    iosBundleId: 'com.itz.aipet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMGGVKpekvx7hIglGOEix69EoIG9JIQrI',
    appId: '1:916090550504:web:0a887fc627a77acbaf715d',
    messagingSenderId: '916090550504',
    projectId: 'aipet-1c44e',
    authDomain: 'aipet-1c44e.firebaseapp.com',
    databaseURL: 'https://aipet-1c44e-default-rtdb.firebaseio.com',
    storageBucket: 'aipet-1c44e.firebasestorage.app',
  );
}
