// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/features/walk/data/repositories/hybrid_walk_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aipet_frontend/features/walk/data/services/walk_api_service.dart'
    as _i3;
import 'package:aipet_frontend/features/walk/domain/entities/walk_record_entity.dart'
    as _i5;
import 'package:aipet_frontend/features/walk/domain/entities/walk_statistics_entity.dart'
    as _i6;
import 'package:aipet_frontend/shared/core/domain/result.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WalkApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalkApiService extends _i1.Mock implements _i3.WalkApiService {
  @override
  _i4.Future<_i2.Result<List<_i5.WalkRecordEntity>>> getAllWalkRecords() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWalkRecords, []),
            returnValue:
                _i4.Future<_i2.Result<List<_i5.WalkRecordEntity>>>.value(
                  _FakeResult_0<List<_i5.WalkRecordEntity>>(
                    this,
                    Invocation.method(#getAllWalkRecords, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Result<List<_i5.WalkRecordEntity>>>.value(
                  _FakeResult_0<List<_i5.WalkRecordEntity>>(
                    this,
                    Invocation.method(#getAllWalkRecords, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i5.WalkRecordEntity>>>);

  @override
  _i4.Future<_i2.Result<_i5.WalkRecordEntity>> getWalkRecordById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getWalkRecordById, [id]),
            returnValue: _i4.Future<_i2.Result<_i5.WalkRecordEntity>>.value(
              _FakeResult_0<_i5.WalkRecordEntity>(
                this,
                Invocation.method(#getWalkRecordById, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Result<_i5.WalkRecordEntity>>.value(
                  _FakeResult_0<_i5.WalkRecordEntity>(
                    this,
                    Invocation.method(#getWalkRecordById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i5.WalkRecordEntity>>);

  @override
  _i4.Future<_i2.Result<List<_i5.WalkRecordEntity>>> getWalkRecordsByPetId(
    String? petId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWalkRecordsByPetId, [petId]),
            returnValue:
                _i4.Future<_i2.Result<List<_i5.WalkRecordEntity>>>.value(
                  _FakeResult_0<List<_i5.WalkRecordEntity>>(
                    this,
                    Invocation.method(#getWalkRecordsByPetId, [petId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Result<List<_i5.WalkRecordEntity>>>.value(
                  _FakeResult_0<List<_i5.WalkRecordEntity>>(
                    this,
                    Invocation.method(#getWalkRecordsByPetId, [petId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i5.WalkRecordEntity>>>);

  @override
  _i4.Future<_i2.Result<_i5.WalkRecordEntity>> startWalk(
    _i5.WalkRecordEntity? walkRecord,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startWalk, [walkRecord]),
            returnValue: _i4.Future<_i2.Result<_i5.WalkRecordEntity>>.value(
              _FakeResult_0<_i5.WalkRecordEntity>(
                this,
                Invocation.method(#startWalk, [walkRecord]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Result<_i5.WalkRecordEntity>>.value(
                  _FakeResult_0<_i5.WalkRecordEntity>(
                    this,
                    Invocation.method(#startWalk, [walkRecord]),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i5.WalkRecordEntity>>);

  @override
  _i4.Future<_i2.Result<_i5.WalkRecordEntity>> endWalk(
    String? walkId, {
    double? distance,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #endWalk,
              [walkId],
              {#distance: distance, #notes: notes},
            ),
            returnValue: _i4.Future<_i2.Result<_i5.WalkRecordEntity>>.value(
              _FakeResult_0<_i5.WalkRecordEntity>(
                this,
                Invocation.method(
                  #endWalk,
                  [walkId],
                  {#distance: distance, #notes: notes},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Result<_i5.WalkRecordEntity>>.value(
                  _FakeResult_0<_i5.WalkRecordEntity>(
                    this,
                    Invocation.method(
                      #endWalk,
                      [walkId],
                      {#distance: distance, #notes: notes},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i5.WalkRecordEntity>>);

  @override
  _i4.Future<_i2.Result<_i5.WalkRecordEntity>> updateWalkRecord(
    _i5.WalkRecordEntity? walkRecord,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWalkRecord, [walkRecord]),
            returnValue: _i4.Future<_i2.Result<_i5.WalkRecordEntity>>.value(
              _FakeResult_0<_i5.WalkRecordEntity>(
                this,
                Invocation.method(#updateWalkRecord, [walkRecord]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Result<_i5.WalkRecordEntity>>.value(
                  _FakeResult_0<_i5.WalkRecordEntity>(
                    this,
                    Invocation.method(#updateWalkRecord, [walkRecord]),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i5.WalkRecordEntity>>);

  @override
  _i4.Future<_i2.Result<void>> deleteWalkRecord(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWalkRecord, [id]),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#deleteWalkRecord, [id]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#deleteWalkRecord, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Result<void>>);

  @override
  _i4.Future<_i2.Result<_i6.WalkStatistics>> getWalkStatistics({
    String? petId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWalkStatistics, [], {
              #petId: petId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Future<_i2.Result<_i6.WalkStatistics>>.value(
              _FakeResult_0<_i6.WalkStatistics>(
                this,
                Invocation.method(#getWalkStatistics, [], {
                  #petId: petId,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Result<_i6.WalkStatistics>>.value(
                  _FakeResult_0<_i6.WalkStatistics>(
                    this,
                    Invocation.method(#getWalkStatistics, [], {
                      #petId: petId,
                      #startDate: startDate,
                      #endDate: endDate,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i6.WalkStatistics>>);

  @override
  _i4.Future<_i2.Result<_i5.WalkRecordEntity?>> getCurrentWalk() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWalk, []),
            returnValue: _i4.Future<_i2.Result<_i5.WalkRecordEntity?>>.value(
              _FakeResult_0<_i5.WalkRecordEntity?>(
                this,
                Invocation.method(#getCurrentWalk, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Result<_i5.WalkRecordEntity?>>.value(
                  _FakeResult_0<_i5.WalkRecordEntity?>(
                    this,
                    Invocation.method(#getCurrentWalk, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<_i5.WalkRecordEntity?>>);
}
