// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/integration/features/splash/splash_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aipet_frontend/features/splash/domain/entities/splash_entity.dart'
    as _i5;
import 'package:aipet_frontend/features/splash/domain/repositories/splash_repository.dart'
    as _i3;
import 'package:aipet_frontend/shared/shared.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SplashRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSplashRepository extends _i1.Mock implements _i3.SplashRepository {
  MockSplashRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.SplashEntity>> getSplashConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getSplashConfig, []),
            returnValue: _i4.Future<_i2.Result<_i5.SplashEntity>>.value(
              _FakeResult_0<_i5.SplashEntity>(
                this,
                Invocation.method(#getSplashConfig, []),
              ),
            ),
          )
          as _i4.Future<_i2.Result<_i5.SplashEntity>>);

  @override
  _i4.Future<_i2.Result<void>> initializeApp() =>
      (super.noSuchMethod(
            Invocation.method(#initializeApp, []),
            returnValue: _i4.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(this, Invocation.method(#initializeApp, [])),
            ),
          )
          as _i4.Future<_i2.Result<void>>);
}
