// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/unit/features/notification/domain/usecases/mark_notification_as_read_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aipet_frontend/features/notification/domain/entities/entities.dart'
    as _i5;
import 'package:aipet_frontend/features/notification/domain/repositories/notification_repository.dart'
    as _i2;
import 'package:aipet_frontend/shared/foundation/result/app_result.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i2.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.NotificationModel>>> getAllNotifications({
    required String? userId,
    int? page = 0,
    int? limit = 20,
    bool? isRead,
    String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotifications, [], {
              #userId: userId,
              #page: page,
              #limit: limit,
              #isRead: isRead,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.NotificationModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.NotificationModel>>>(
                    this,
                    Invocation.method(#getAllNotifications, [], {
                      #userId: userId,
                      #page: page,
                      #limit: limit,
                      #isRead: isRead,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.NotificationModel>>>);

  @override
  _i3.Future<_i4.Result<_i5.NotificationModel?>> getNotificationById({
    required String? userId,
    required String? notificationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationById, [], {
              #userId: userId,
              #notificationId: notificationId,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.NotificationModel?>>.value(
              _i6.dummyValue<_i4.Result<_i5.NotificationModel?>>(
                this,
                Invocation.method(#getNotificationById, [], {
                  #userId: userId,
                  #notificationId: notificationId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.NotificationModel?>>);

  @override
  _i3.Future<_i4.Result<bool>> markAsRead({
    required String? userId,
    required String? notificationId,
    required bool? isRead,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [], {
              #userId: userId,
              #notificationId: notificationId,
              #isRead: isRead,
            }),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#markAsRead, [], {
                  #userId: userId,
                  #notificationId: notificationId,
                  #isRead: isRead,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<bool>> deleteNotification({
    required String? userId,
    required String? notificationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [], {
              #userId: userId,
              #notificationId: notificationId,
            }),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#deleteNotification, [], {
                  #userId: userId,
                  #notificationId: notificationId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> getNotificationSettings(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationSettings, [userId]),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i6.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#getNotificationSettings, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i4.Result<bool>> updateNotificationSettings({
    required String? userId,
    required Map<String, dynamic>? settings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotificationSettings, [], {
              #userId: userId,
              #settings: settings,
            }),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#updateNotificationSettings, [], {
                  #userId: userId,
                  #settings: settings,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> getNotificationStats(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationStats, [userId]),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i6.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#getNotificationStats, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);
}
