// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/unit/features/home/domain/usecases/get_dashboard_data_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aipet_frontend/features/home/domain/repositories/home_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i2.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> getDashboardData() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardData, []),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> getCurrentWeather({
    dynamic location,
    bool? userTriggered = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWeather, [], {
              #location: location,
              #userTriggered: userTriggered,
            }),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<List<dynamic>> getPetSummaries() =>
      (super.noSuchMethod(
            Invocation.method(#getPetSummaries, []),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<dynamic> getWalkSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getWalkSummary, []),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> getPetHealthSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getPetHealthSummary, []),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<List<dynamic>> getUpcomingAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingAppointments, []),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);
}
