// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/unit/features/home/domain/usecases/get_pet_summary_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aipet_frontend/features/home/domain/entities/entities.dart'
    as _i2;
import 'package:aipet_frontend/features/home/domain/repositories/home_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeDashboardEntity_0 extends _i1.SmartFake
    implements _i2.HomeDashboardEntity {
  _FakeHomeDashboardEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalkSummary_1 extends _i1.SmartFake implements _i2.WalkSummary {
  _FakeWalkSummary_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthSummary_2 extends _i1.SmartFake implements _i2.HealthSummary {
  _FakeHealthSummary_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i3.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HomeDashboardEntity> getDashboardData() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardData, []),
            returnValue: _i4.Future<_i2.HomeDashboardEntity>.value(
              _FakeHomeDashboardEntity_0(
                this,
                Invocation.method(#getDashboardData, []),
              ),
            ),
          )
          as _i4.Future<_i2.HomeDashboardEntity>);

  @override
  _i4.Future<_i2.WeatherEntity?> getCurrentWeather({
    _i2.WeatherLocationEntity? location,
    bool? userTriggered = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWeather, [], {
              #location: location,
              #userTriggered: userTriggered,
            }),
            returnValue: _i4.Future<_i2.WeatherEntity?>.value(),
          )
          as _i4.Future<_i2.WeatherEntity?>);

  @override
  _i4.Future<List<_i2.PetSummaryEntity>> getPetSummaries() =>
      (super.noSuchMethod(
            Invocation.method(#getPetSummaries, []),
            returnValue: _i4.Future<List<_i2.PetSummaryEntity>>.value(
              <_i2.PetSummaryEntity>[],
            ),
          )
          as _i4.Future<List<_i2.PetSummaryEntity>>);

  @override
  _i4.Future<_i2.WalkSummary> getWalkSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getWalkSummary, []),
            returnValue: _i4.Future<_i2.WalkSummary>.value(
              _FakeWalkSummary_1(this, Invocation.method(#getWalkSummary, [])),
            ),
          )
          as _i4.Future<_i2.WalkSummary>);

  @override
  _i4.Future<_i2.HealthSummary> getPetHealthSummary() =>
      (super.noSuchMethod(
            Invocation.method(#getPetHealthSummary, []),
            returnValue: _i4.Future<_i2.HealthSummary>.value(
              _FakeHealthSummary_2(
                this,
                Invocation.method(#getPetHealthSummary, []),
              ),
            ),
          )
          as _i4.Future<_i2.HealthSummary>);

  @override
  _i4.Future<List<_i2.AppointmentSummary>> getUpcomingAppointments() =>
      (super.noSuchMethod(
            Invocation.method(#getUpcomingAppointments, []),
            returnValue: _i4.Future<List<_i2.AppointmentSummary>>.value(
              <_i2.AppointmentSummary>[],
            ),
          )
          as _i4.Future<List<_i2.AppointmentSummary>>);
}
