// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/unit/features/home/domain/usecases/get_weather_data_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aipet_frontend/features/home/domain/entities/home_dashboard_entity.dart'
    as _i5;
import 'package:aipet_frontend/features/home/domain/repositories/home_repository.dart'
    as _i2;
import 'package:aipet_frontend/shared/foundation/result/app_result.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i2.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.HomeDashboardEntity>> getDashboardData(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardData, [userId]),
            returnValue: _i3.Future<_i4.Result<_i5.HomeDashboardEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.HomeDashboardEntity>>(
                this,
                Invocation.method(#getDashboardData, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.HomeDashboardEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.WeatherEntity?>> getWeatherData(String? location) =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherData, [location]),
            returnValue: _i3.Future<_i4.Result<_i5.WeatherEntity?>>.value(
              _i6.dummyValue<_i4.Result<_i5.WeatherEntity?>>(
                this,
                Invocation.method(#getWeatherData, [location]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.WeatherEntity?>>);

  @override
  _i3.Future<_i4.Result<List<_i5.PetSummaryEntity>>> getPetSummaries(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPetSummaries, [userId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.PetSummaryEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.PetSummaryEntity>>>(
                    this,
                    Invocation.method(#getPetSummaries, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.PetSummaryEntity>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.TodayAppointmentEntity>>> getTodayAppointments(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayAppointments, [userId]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.TodayAppointmentEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.TodayAppointmentEntity>>>(
                    this,
                    Invocation.method(#getTodayAppointments, [userId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.TodayAppointmentEntity>>>);

  @override
  _i3.Future<_i4.Result<int>> getTotalWalkMinutes(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalWalkMinutes, [userId]),
            returnValue: _i3.Future<_i4.Result<int>>.value(
              _i6.dummyValue<_i4.Result<int>>(
                this,
                Invocation.method(#getTotalWalkMinutes, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<int>>);
}
