// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/unit/features/ai/data/repositories/ai_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:aipet_frontend/features/ai/data/services/ai_mock_data_service_impl.dart'
    as _i7;
import 'package:aipet_frontend/features/ai/data/services/openai_service.dart'
    as _i4;
import 'package:aipet_frontend/features/ai/domain/domain.dart' as _i8;
import 'package:aipet_frontend/shared/domain/entities/entities.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:riverpod/src/internals.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProviderContainer_1 extends _i1.SmartFake
    implements _i3.ProviderContainer {
  _FakeProviderContainer_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKeepAliveLink_2 extends _i1.SmartFake implements _i3.KeepAliveLink {
  _FakeKeepAliveLink_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProviderSubscription_3<State1> extends _i1.SmartFake
    implements _i3.ProviderSubscription<State1> {
  _FakeProviderSubscription_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OpenAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAIService extends _i1.Mock implements _i4.OpenAIService {
  MockOpenAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<String> generateResponse(
    String? message, {
    _i5.PetProfileEntity? petContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateResponse,
              [message],
              {#petContext: petContext},
            ),
            returnValue: _i2.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #generateResponse,
                  [message],
                  {#petContext: petContext},
                ),
              ),
            ),
          )
          as _i2.Future<String>);

  @override
  void logError(String? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#logError, [message, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void logInfo(String? message) => super.noSuchMethod(
    Invocation.method(#logInfo, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logWarning(String? message) => super.noSuchMethod(
    Invocation.method(#logWarning, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void logDebug(String? message) => super.noSuchMethod(
    Invocation.method(#logDebug, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void recordPerformanceMetric(String? operation, Duration? duration) =>
      super.noSuchMethod(
        Invocation.method(#recordPerformanceMetric, [operation, duration]),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Future<T> trackApiPerformance<T>(
    String? operation,
    _i2.Future<T> Function()? apiCall,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#trackApiPerformance, [operation, apiCall]),
            returnValue:
                _i6.ifNotNull(
                  _i6.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#trackApiPerformance, [
                      operation,
                      apiCall,
                    ]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#trackApiPerformance, [operation, apiCall]),
                ),
          )
          as _i2.Future<T>);
}

/// A class which mocks [AiMockDataServiceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiMockDataServiceImpl extends _i1.Mock
    implements _i7.AiMockDataServiceImpl {
  MockAiMockDataServiceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> simulateApiDelay({int? seconds = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#simulateApiDelay, [], {#seconds: seconds}),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<List<Map<String, dynamic>>> getChatHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistory, []),
            returnValue: _i2.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i2.Future<List<Map<String, dynamic>>>);

  @override
  _i2.Future<List<Map<String, dynamic>>> getSuggestedQuestions() =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedQuestions, []),
            returnValue: _i2.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i2.Future<List<Map<String, dynamic>>>);

  @override
  _i2.Future<List<Map<String, dynamic>>> getFavoriteQAs() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteQAs, []),
            returnValue: _i2.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i2.Future<List<Map<String, dynamic>>>);

  @override
  _i2.Future<List<Map<String, dynamic>>> getChatSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getChatSessions, []),
            returnValue: _i2.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i2.Future<List<Map<String, dynamic>>>);

  @override
  _i2.Future<List<_i8.AiMessageEntity>> getChatHistoryEntities() =>
      (super.noSuchMethod(
            Invocation.method(#getChatHistoryEntities, []),
            returnValue: _i2.Future<List<_i8.AiMessageEntity>>.value(
              <_i8.AiMessageEntity>[],
            ),
          )
          as _i2.Future<List<_i8.AiMessageEntity>>);

  @override
  _i2.Future<List<_i8.AiSuggestedQuestionEntity>>
  getSuggestedQuestionEntities() =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestedQuestionEntities, []),
            returnValue: _i2.Future<List<_i8.AiSuggestedQuestionEntity>>.value(
              <_i8.AiSuggestedQuestionEntity>[],
            ),
          )
          as _i2.Future<List<_i8.AiSuggestedQuestionEntity>>);

  @override
  _i2.Future<List<_i8.AiFavoriteQaEntity>> getFavoriteQAEntities() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteQAEntities, []),
            returnValue: _i2.Future<List<_i8.AiFavoriteQaEntity>>.value(
              <_i8.AiFavoriteQaEntity>[],
            ),
          )
          as _i2.Future<List<_i8.AiFavoriteQaEntity>>);

  @override
  _i2.Future<List<_i8.AiChatSessionEntity>> getChatSessionEntities() =>
      (super.noSuchMethod(
            Invocation.method(#getChatSessionEntities, []),
            returnValue: _i2.Future<List<_i8.AiChatSessionEntity>>.value(
              <_i8.AiChatSessionEntity>[],
            ),
          )
          as _i2.Future<List<_i8.AiChatSessionEntity>>);

  @override
  _i2.Future<Map<String, dynamic>> generateAiResponse(String? userMessage) =>
      (super.noSuchMethod(
            Invocation.method(#generateAiResponse, [userMessage]),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<Map<String, dynamic>> createChatSession(
    String? title, {
    String? petId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChatSession, [title], {#petId: petId}),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<List<T>> getMockData<T>(String? dataType) =>
      (super.noSuchMethod(
            Invocation.method(#getMockData, [dataType]),
            returnValue: _i2.Future<List<T>>.value(<T>[]),
          )
          as _i2.Future<List<T>>);

  @override
  _i2.Future<T?> getMockDataById<T>(String? dataType, String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMockDataById, [dataType, id]),
            returnValue: _i2.Future<T?>.value(),
          )
          as _i2.Future<T?>);
}

/// A class which mocks [Ref].
///
/// See the documentation for Mockito's code generation for more information.
class MockRef<State extends Object?> extends _i1.Mock
    implements _i3.Ref<State> {
  MockRef() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ProviderContainer get container =>
      (super.noSuchMethod(
            Invocation.getter(#container),
            returnValue: _FakeProviderContainer_1(
              this,
              Invocation.getter(#container),
            ),
          )
          as _i3.ProviderContainer);

  @override
  T refresh<T>(_i3.Refreshable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [provider]),
            returnValue: _i6.dummyValue<T>(
              this,
              Invocation.method(#refresh, [provider]),
            ),
          )
          as T);

  @override
  void invalidate(_i3.ProviderOrFamily? provider) => super.noSuchMethod(
    Invocation.method(#invalidate, [provider]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void listenSelf(
    void Function(State?, State)? listener, {
    void Function(Object, StackTrace)? onError,
  }) => super.noSuchMethod(
    Invocation.method(#listenSelf, [listener], {#onError: onError}),
    returnValueForMissingStub: null,
  );

  @override
  void invalidateSelf() => super.noSuchMethod(
    Invocation.method(#invalidateSelf, []),
    returnValueForMissingStub: null,
  );

  @override
  void onAddListener(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onAddListener, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onRemoveListener(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onRemoveListener, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onResume(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onResume, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onCancel(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onCancel, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  void onDispose(void Function()? cb) => super.noSuchMethod(
    Invocation.method(#onDispose, [cb]),
    returnValueForMissingStub: null,
  );

  @override
  T read<T>(_i3.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#read, [provider]),
            returnValue: _i6.dummyValue<T>(
              this,
              Invocation.method(#read, [provider]),
            ),
          )
          as T);

  @override
  bool exists(_i3.ProviderBase<Object?>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [provider]),
            returnValue: false,
          )
          as bool);

  @override
  T watch<T>(_i3.ProviderListenable<T>? provider) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [provider]),
            returnValue: _i6.dummyValue<T>(
              this,
              Invocation.method(#watch, [provider]),
            ),
          )
          as T);

  @override
  _i3.KeepAliveLink keepAlive() =>
      (super.noSuchMethod(
            Invocation.method(#keepAlive, []),
            returnValue: _FakeKeepAliveLink_2(
              this,
              Invocation.method(#keepAlive, []),
            ),
          )
          as _i3.KeepAliveLink);

  @override
  _i3.ProviderSubscription<T> listen<T>(
    _i3.ProviderListenable<T>? provider,
    void Function(T?, T)? listener, {
    void Function(Object, StackTrace)? onError,
    bool? fireImmediately,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [provider, listener],
              {#onError: onError, #fireImmediately: fireImmediately},
            ),
            returnValue: _FakeProviderSubscription_3<T>(
              this,
              Invocation.method(
                #listen,
                [provider, listener],
                {#onError: onError, #fireImmediately: fireImmediately},
              ),
            ),
          )
          as _i3.ProviderSubscription<T>);
}
