import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// PDF 푸터 빌더
///
/// PDF 푸터 관련 위젯을 생성하는 책임을 가진 클래스
class PdfFooterBuilder {
  /// 푸터 빌드
  pw.Widget buildFooter() {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 15),
      decoration: const pw.BoxDecoration(
        color: PdfColor.fromInt(0xCCFFFFFF), // 80% 불투명도
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        children: [
          pw.Text(
            '※ このレポートは参考情報です。気になる症状がある場合は、必ず獣医師にご相談ください。',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
            textAlign: pw.TextAlign.center,
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Generated by AI Pet Health Management System',
            style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey600),
            textAlign: pw.TextAlign.center,
          ),
        ],
      ),
    );
  }

  /// 간단한 푸터 빌드 (심플 PDF용)
  pw.Widget buildSimpleFooter() {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(5),
      ),
      child: pw.Column(
        children: [
          pw.Text(
            '※ このレポートは参考情報です。気になる症状がある場合は、必ず獣医師にご相談ください。',
            style: const pw.TextStyle(fontSize: 8),
            textAlign: pw.TextAlign.center,
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Generated by AI Pet Health Management System',
            style: const pw.TextStyle(fontSize: 7),
            textAlign: pw.TextAlign.center,
          ),
        ],
      ),
    );
  }
}
