// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/unit/features/settings/domain/usecases/update_user_profile_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aipet_frontend/features/settings/domain/entities/user_profile_entity.dart'
    as _i5;
import 'package:aipet_frontend/features/settings/domain/repositories/settings_repository.dart'
    as _i2;
import 'package:aipet_frontend/shared/shared.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.UserProfileEntity>> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i3.Future<_i4.Result<_i5.UserProfileEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserProfileEntity>>(
                this,
                Invocation.method(#getUserProfile, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserProfileEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.UserProfileEntity>> updateUserProfile(
    _i5.UserProfileEntity? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [profile]),
            returnValue: _i3.Future<_i4.Result<_i5.UserProfileEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserProfileEntity>>(
                this,
                Invocation.method(#updateUserProfile, [profile]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserProfileEntity>>);

  @override
  _i3.Future<_i4.Result<void>> changePassword(
    _i5.PasswordChangeRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.AppSettingsEntity>> getAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getAppSettings, []),
            returnValue: _i3.Future<_i4.Result<_i5.AppSettingsEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.AppSettingsEntity>>(
                this,
                Invocation.method(#getAppSettings, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AppSettingsEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.AppSettingsEntity>> saveAppSettings(
    _i5.AppSettingsEntity? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppSettings, [settings]),
            returnValue: _i3.Future<_i4.Result<_i5.AppSettingsEntity>>.value(
              _i6.dummyValue<_i4.Result<_i5.AppSettingsEntity>>(
                this,
                Invocation.method(#saveAppSettings, [settings]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AppSettingsEntity>>);

  @override
  _i3.Future<_i4.Result<_i5.DataExportResult>> exportAppData() =>
      (super.noSuchMethod(
            Invocation.method(#exportAppData, []),
            returnValue: _i3.Future<_i4.Result<_i5.DataExportResult>>.value(
              _i6.dummyValue<_i4.Result<_i5.DataExportResult>>(
                this,
                Invocation.method(#exportAppData, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.DataExportResult>>);

  @override
  _i3.Future<_i4.Result<void>> importAppData(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#importAppData, [filePath]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#importAppData, [filePath]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> clearAppCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAppCache, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#clearAppCache, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<int>> getCacheSize() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheSize, []),
            returnValue: _i3.Future<_i4.Result<int>>.value(
              _i6.dummyValue<_i4.Result<int>>(
                this,
                Invocation.method(#getCacheSize, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<int>>);
}
