// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/integration/facility_notification_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:aipet_frontend/features/facility/domain/entities/facility_entity.dart'
    as _i5;
import 'package:aipet_frontend/features/facility/domain/repositories/facility_repository.dart'
    as _i2;
import 'package:aipet_frontend/features/notification/domain/entities/entities.dart'
    as _i8;
import 'package:aipet_frontend/features/notification/domain/repositories/notification_repository.dart'
    as _i7;
import 'package:aipet_frontend/shared/shared.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FacilityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFacilityRepository extends _i1.Mock
    implements _i2.FacilityRepository {
  MockFacilityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Facility>>> getNearbyFacilities() =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyFacilities, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.Facility>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Facility>>>(
                this,
                Invocation.method(#getNearbyFacilities, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Facility>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Facility>>> searchFacilities(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchFacilities, [query]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Facility>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Facility>>>(
                this,
                Invocation.method(#searchFacilities, [query]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Facility>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Facility>>> getFacilitiesByType(
    _i5.FacilityType? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFacilitiesByType, [type]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Facility>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Facility>>>(
                this,
                Invocation.method(#getFacilitiesByType, [type]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Facility>>>);

  @override
  _i3.Future<_i4.Result<_i5.Facility>> getFacilityById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFacilityById, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.Facility>>.value(
              _i6.dummyValue<_i4.Result<_i5.Facility>>(
                this,
                Invocation.method(#getFacilityById, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Facility>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Facility>>> getFacilitiesInRadius(
    double? latitude,
    double? longitude,
    double? radius,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFacilitiesInRadius, [
              latitude,
              longitude,
              radius,
            ]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Facility>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Facility>>>(
                this,
                Invocation.method(#getFacilitiesInRadius, [
                  latitude,
                  longitude,
                  radius,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Facility>>>);

  @override
  _i3.Future<_i4.Result<void>> setCurrentLocation(
    double? latitude,
    double? longitude,
    String? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentLocation, [
              latitude,
              longitude,
              address,
            ]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#setCurrentLocation, [
                  latitude,
                  longitude,
                  address,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i7.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i8.NotificationModel>>> getAllNotifications({
    required String? userId,
    int? page = 0,
    int? limit = 20,
    bool? isRead,
    String? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotifications, [], {
              #userId: userId,
              #page: page,
              #limit: limit,
              #isRead: isRead,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.Result<List<_i8.NotificationModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i8.NotificationModel>>>(
                    this,
                    Invocation.method(#getAllNotifications, [], {
                      #userId: userId,
                      #page: page,
                      #limit: limit,
                      #isRead: isRead,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i8.NotificationModel>>>);

  @override
  _i3.Future<_i4.Result<_i8.NotificationModel?>> getNotificationById({
    required String? userId,
    required String? notificationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationById, [], {
              #userId: userId,
              #notificationId: notificationId,
            }),
            returnValue: _i3.Future<_i4.Result<_i8.NotificationModel?>>.value(
              _i6.dummyValue<_i4.Result<_i8.NotificationModel?>>(
                this,
                Invocation.method(#getNotificationById, [], {
                  #userId: userId,
                  #notificationId: notificationId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.NotificationModel?>>);

  @override
  _i3.Future<_i4.Result<bool>> markAsRead({
    required String? userId,
    required String? notificationId,
    required bool? isRead,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [], {
              #userId: userId,
              #notificationId: notificationId,
              #isRead: isRead,
            }),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#markAsRead, [], {
                  #userId: userId,
                  #notificationId: notificationId,
                  #isRead: isRead,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<bool>> deleteNotification({
    required String? userId,
    required String? notificationId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [], {
              #userId: userId,
              #notificationId: notificationId,
            }),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#deleteNotification, [], {
                  #userId: userId,
                  #notificationId: notificationId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> getNotificationSettings(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationSettings, [userId]),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i6.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#getNotificationSettings, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);

  @override
  _i3.Future<_i4.Result<bool>> updateNotificationSettings({
    required String? userId,
    required Map<String, dynamic>? settings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotificationSettings, [], {
              #userId: userId,
              #settings: settings,
            }),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#updateNotificationSettings, [], {
                  #userId: userId,
                  #settings: settings,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<Map<String, dynamic>>> getNotificationStats(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationStats, [userId]),
            returnValue: _i3.Future<_i4.Result<Map<String, dynamic>>>.value(
              _i6.dummyValue<_i4.Result<Map<String, dynamic>>>(
                this,
                Invocation.method(#getNotificationStats, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, dynamic>>>);
}
