// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/features/home/presentation/services/home_data_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aipet_frontend/features/home/domain/entities/entities.dart'
    as _i2;
import 'package:aipet_frontend/features/home/domain/usecases/get_appointment_summary_usecase.dart'
    as _i9;
import 'package:aipet_frontend/features/home/domain/usecases/get_dashboard_data_usecase.dart'
    as _i3;
import 'package:aipet_frontend/features/home/domain/usecases/get_health_summary_usecase.dart'
    as _i8;
import 'package:aipet_frontend/features/home/domain/usecases/get_pet_summary_usecase.dart'
    as _i5;
import 'package:aipet_frontend/features/home/domain/usecases/get_walk_summary_usecase.dart'
    as _i7;
import 'package:aipet_frontend/features/home/domain/usecases/get_weather_data_usecase.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeDashboardEntity_0 extends _i1.SmartFake
    implements _i2.HomeDashboardEntity {
  _FakeHomeDashboardEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalkSummary_1 extends _i1.SmartFake implements _i2.WalkSummary {
  _FakeWalkSummary_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHealthSummary_2 extends _i1.SmartFake implements _i2.HealthSummary {
  _FakeHealthSummary_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetDashboardDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDashboardDataUseCase extends _i1.Mock
    implements _i3.GetDashboardDataUseCase {
  MockGetDashboardDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HomeDashboardEntity> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.HomeDashboardEntity>.value(
              _FakeHomeDashboardEntity_0(this, Invocation.method(#call, [])),
            ),
          )
          as _i4.Future<_i2.HomeDashboardEntity>);
}

/// A class which mocks [GetPetSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPetSummaryUseCase extends _i1.Mock
    implements _i5.GetPetSummaryUseCase {
  MockGetPetSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.PetSummaryEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i2.PetSummaryEntity>>.value(
              <_i2.PetSummaryEntity>[],
            ),
          )
          as _i4.Future<List<_i2.PetSummaryEntity>>);
}

/// A class which mocks [GetWeatherDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWeatherDataUseCase extends _i1.Mock
    implements _i6.GetWeatherDataUseCase {
  MockGetWeatherDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherEntity?> call({
    _i2.WeatherLocationEntity? location,
    bool? userTriggered = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #location: location,
              #userTriggered: userTriggered,
            }),
            returnValue: _i4.Future<_i2.WeatherEntity?>.value(),
          )
          as _i4.Future<_i2.WeatherEntity?>);
}

/// A class which mocks [GetWalkSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWalkSummaryUseCase extends _i1.Mock
    implements _i7.GetWalkSummaryUseCase {
  MockGetWalkSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WalkSummary> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.WalkSummary>.value(
              _FakeWalkSummary_1(this, Invocation.method(#call, [])),
            ),
          )
          as _i4.Future<_i2.WalkSummary>);
}

/// A class which mocks [GetHealthSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHealthSummaryUseCase extends _i1.Mock
    implements _i8.GetHealthSummaryUseCase {
  MockGetHealthSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HealthSummary> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.HealthSummary>.value(
              _FakeHealthSummary_2(this, Invocation.method(#call, [])),
            ),
          )
          as _i4.Future<_i2.HealthSummary>);
}

/// A class which mocks [GetAppointmentSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAppointmentSummaryUseCase extends _i1.Mock
    implements _i9.GetAppointmentSummaryUseCase {
  MockGetAppointmentSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.AppointmentSummary>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i2.AppointmentSummary>>.value(
              <_i2.AppointmentSummary>[],
            ),
          )
          as _i4.Future<List<_i2.AppointmentSummary>>);
}
