// Mocks generated by Mockito 5.4.6 from annotations
// in aipet_frontend/test/features/home/presentation/services/home_data_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aipet_frontend/features/home/domain/entities/home_dashboard_entity.dart'
    as _i6;
import 'package:aipet_frontend/features/home/domain/entities/pet_summary_entity.dart'
    as _i9;
import 'package:aipet_frontend/features/home/domain/entities/weather_entity.dart'
    as _i11;
import 'package:aipet_frontend/features/home/domain/repositories/home_repository.dart'
    as _i2;
import 'package:aipet_frontend/features/home/domain/usecases/get_appointment_summary_usecase.dart'
    as _i14;
import 'package:aipet_frontend/features/home/domain/usecases/get_dashboard_data_usecase.dart'
    as _i3;
import 'package:aipet_frontend/features/home/domain/usecases/get_health_summary_usecase.dart'
    as _i13;
import 'package:aipet_frontend/features/home/domain/usecases/get_pet_summary_usecase.dart'
    as _i8;
import 'package:aipet_frontend/features/home/domain/usecases/get_walk_summary_usecase.dart'
    as _i12;
import 'package:aipet_frontend/features/home/domain/usecases/get_weather_data_usecase.dart'
    as _i10;
import 'package:aipet_frontend/shared/foundation/result/app_result.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHomeRepository_0 extends _i1.SmartFake
    implements _i2.HomeRepository {
  _FakeHomeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetDashboardDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDashboardDataUseCase extends _i1.Mock
    implements _i3.GetDashboardDataUseCase {
  MockGetDashboardDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i4.Future<_i5.Result<_i6.HomeDashboardEntity>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<_i6.HomeDashboardEntity>>.value(
              _i7.dummyValue<_i5.Result<_i6.HomeDashboardEntity>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.HomeDashboardEntity>>);
}

/// A class which mocks [GetPetSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPetSummaryUseCase extends _i1.Mock
    implements _i8.GetPetSummaryUseCase {
  MockGetPetSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i4.Future<_i5.Result<List<_i9.PetSummaryEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.Result<List<_i9.PetSummaryEntity>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i9.PetSummaryEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i9.PetSummaryEntity>>>);

  @override
  _i4.Future<_i5.Result<_i9.PetSummaryEntity>> getById(String? petId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [petId]),
            returnValue: _i4.Future<_i5.Result<_i9.PetSummaryEntity>>.value(
              _i7.dummyValue<_i5.Result<_i9.PetSummaryEntity>>(
                this,
                Invocation.method(#getById, [petId]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i9.PetSummaryEntity>>);
}

/// A class which mocks [GetWeatherDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWeatherDataUseCase extends _i1.Mock
    implements _i10.GetWeatherDataUseCase {
  MockGetWeatherDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i4.Future<_i5.Result<_i11.WeatherEntity?>> call({
    _i11.WeatherLocationEntity? location,
    bool? userTriggered = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #location: location,
              #userTriggered: userTriggered,
            }),
            returnValue: _i4.Future<_i5.Result<_i11.WeatherEntity?>>.value(
              _i7.dummyValue<_i5.Result<_i11.WeatherEntity?>>(
                this,
                Invocation.method(#call, [], {
                  #location: location,
                  #userTriggered: userTriggered,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i11.WeatherEntity?>>);
}

/// A class which mocks [GetWalkSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWalkSummaryUseCase extends _i1.Mock
    implements _i12.GetWalkSummaryUseCase {
  MockGetWalkSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i4.Future<_i5.Result<_i6.WalkSummary>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<_i6.WalkSummary>>.value(
              _i7.dummyValue<_i5.Result<_i6.WalkSummary>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.WalkSummary>>);
}

/// A class which mocks [GetHealthSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHealthSummaryUseCase extends _i1.Mock
    implements _i13.GetHealthSummaryUseCase {
  MockGetHealthSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i4.Future<_i5.Result<_i6.HealthSummary>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i5.Result<_i6.HealthSummary>>.value(
              _i7.dummyValue<_i5.Result<_i6.HealthSummary>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<_i6.HealthSummary>>);
}

/// A class which mocks [GetAppointmentSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAppointmentSummaryUseCase extends _i1.Mock
    implements _i14.GetAppointmentSummaryUseCase {
  MockGetAppointmentSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.HomeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeHomeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.HomeRepository);

  @override
  _i4.Future<_i5.Result<List<_i6.AppointmentSummary>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i5.Result<List<_i6.AppointmentSummary>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i6.AppointmentSummary>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i6.AppointmentSummary>>>);
}
